// Autogenerated from:
//   cargo run --example extract_assets -- path/to/components_assets.brdb crates/brdb/src/assets/external.rs
//
// External asset references the game embeds by name (weapons, pickups,
// projectiles, audio/font descriptors), grouped by asset type. Each asset has
// a named `BString` constant; each type has a `&[BString]` slice of its assets.

use crate::wrapper::BString;

// === BRItemBase (88) ===
pub const BP_ITEM_BASE: BString = BString::str("BP_ItemBase");
pub const WEAPON_AP_CARBINE: BString = BString::str("Weapon_APCarbine");
pub const WEAPON_ANTI_MATERIEL_RIFLE: BString = BString::str("Weapon_AntiMaterielRifle");
pub const WEAPON_ARMING_SWORD: BString = BString::str("Weapon_ArmingSword");
pub const WEAPON_ASSAULT_RIFLE: BString = BString::str("Weapon_AssaultRifle");
pub const WEAPON_AUTO_SHOTGUN: BString = BString::str("Weapon_AutoShotgun");
pub const WEAPON_BANDAGE: BString = BString::str("Weapon_Bandage");
pub const WEAPON_BATTLEAXE: BString = BString::str("Weapon_Battleaxe");
pub const WEAPON_BAZOOKA: BString = BString::str("Weapon_Bazooka");
pub const WEAPON_BOLT_ACTION_RIFLE: BString = BString::str("Weapon_BoltActionRifle");
pub const WEAPON_BOW: BString = BString::str("Weapon_Bow");
pub const WEAPON_BOX_PISTOL: BString = BString::str("Weapon_BoxPistol");
pub const WEAPON_BULLPUP_RIFLE: BString = BString::str("Weapon_BullpupRifle");
pub const WEAPON_BULLPUP_SMG: BString = BString::str("Weapon_BullpupSMG");
pub const WEAPON_CHARGED_LONGSWORD: BString = BString::str("Weapon_ChargedLongsword");
pub const WEAPON_CLAWS: BString = BString::str("Weapon_Claws");
pub const WEAPON_COACH_GUN: BString = BString::str("Weapon_CoachGun");
pub const WEAPON_CRYSTAL_KALIS: BString = BString::str("Weapon_CrystalKalis");
pub const WEAPON_DERRINGER: BString = BString::str("Weapon_Derringer");
pub const WEAPON_DYNAMITE: BString = BString::str("Weapon_Dynamite");
pub const WEAPON_FLINTLOCK_PISTOL: BString = BString::str("Weapon_FlintlockPistol");
pub const WEAPON_GRENADE_LAUNCHER: BString = BString::str("Weapon_GrenadeLauncher");
pub const WEAPON_GUARD_PISTOL: BString = BString::str("Weapon_GuardPistol");
pub const WEAPON_HANDAXE: BString = BString::str("Weapon_Handaxe");
pub const WEAPON_HEALTH_POTION: BString = BString::str("Weapon_HealthPotion");
pub const WEAPON_HEAVY_ASSAULT_RIFLE: BString = BString::str("Weapon_HeavyAssaultRifle");
pub const WEAPON_HEAVY_SMG: BString = BString::str("Weapon_HeavySMG");
pub const WEAPON_HERO_SWORD: BString = BString::str("Weapon_HeroSword");
pub const WEAPON_HIGH_POWER_PISTOL: BString = BString::str("Weapon_HighPowerPistol");
pub const WEAPON_HOLO_BLADE: BString = BString::str("Weapon_HoloBlade");
pub const WEAPON_HUNTING_SHOTGUN: BString = BString::str("Weapon_HuntingShotgun");
pub const WEAPON_IMPACT_GRENADE: BString = BString::str("Weapon_ImpactGrenade");
pub const WEAPON_IMPULSE_GRENADE: BString = BString::str("Weapon_ImpulseGrenade");
pub const WEAPON_KNIFE: BString = BString::str("Weapon_Knife");
pub const WEAPON_LASER_AXE: BString = BString::str("Weapon_LaserAxe");
pub const WEAPON_LASER_CLEAVER: BString = BString::str("Weapon_LaserCleaver");
pub const WEAPON_LEVER_ACTION_RIFLE: BString = BString::str("Weapon_LeverActionRifle");
pub const WEAPON_LIGHT_MACHINE_GUN: BString = BString::str("Weapon_LightMachineGun");
pub const WEAPON_LONGSWORD: BString = BString::str("Weapon_Longsword");
pub const WEAPON_MAGNUM_PISTOL: BString = BString::str("Weapon_MagnumPistol");
pub const WEAPON_MEDI_SYRINGE: BString = BString::str("Weapon_MediSyringe");
pub const WEAPON_MICRO_SMG: BString = BString::str("Weapon_MicroSMG");
pub const WEAPON_MINIGUN: BString = BString::str("Weapon_Minigun");
pub const WEAPON_MISSILE_LAUNCHER: BString = BString::str("Weapon_MissileLauncher");
pub const WEAPON_PDW: BString = BString::str("Weapon_PDW");
pub const WEAPON_PICKAXE: BString = BString::str("Weapon_Pickaxe");
pub const WEAPON_PIPE_BOMB: BString = BString::str("Weapon_PipeBomb");
pub const WEAPON_PISTOL: BString = BString::str("Weapon_Pistol");
pub const WEAPON_PLASMA_PISTOL: BString = BString::str("Weapon_PlasmaPistol");
pub const WEAPON_PLASMA_SMG: BString = BString::str("Weapon_PlasmaSMG");
pub const WEAPON_PULSE_CARBINE: BString = BString::str("Weapon_PulseCarbine");
pub const WEAPON_PULSE_RIFLE: BString = BString::str("Weapon_PulseRifle");
pub const WEAPON_QUAD_LAUNCHER: BString = BString::str("Weapon_QuadLauncher");
pub const WEAPON_REVOLVER: BString = BString::str("Weapon_Revolver");
pub const WEAPON_ROAD_FLARE: BString = BString::str("Weapon_RoadFlare");
pub const WEAPON_ROCKET_JUMPER: BString = BString::str("Weapon_RocketJumper");
pub const WEAPON_ROCKET_LAUNCHER: BString = BString::str("Weapon_RocketLauncher");
pub const WEAPON_SABRE: BString = BString::str("Weapon_Sabre");
pub const WEAPON_SEMI_AUTO_RIFLE: BString = BString::str("Weapon_SemiAutoRifle");
pub const WEAPON_SERVICE_RIFLE: BString = BString::str("Weapon_ServiceRifle");
pub const WEAPON_SHADOW_CLAWS: BString = BString::str("Weapon_ShadowClaws");
pub const WEAPON_SHARP_CLAWS: BString = BString::str("Weapon_SharpClaws");
pub const WEAPON_SHOTGUN: BString = BString::str("Weapon_Shotgun");
pub const WEAPON_SLUG_SHOTGUN: BString = BString::str("Weapon_SlugShotgun");
pub const WEAPON_SMOKE_GRENADE: BString = BString::str("Weapon_SmokeGrenade");
pub const WEAPON_SNIPER: BString = BString::str("Weapon_Sniper");
pub const WEAPON_SODA_CAN: BString = BString::str("Weapon_SodaCan");
pub const WEAPON_SPATHA: BString = BString::str("Weapon_Spatha");
pub const WEAPON_SPEAR: BString = BString::str("Weapon_Spear");
pub const WEAPON_SPORTING_SHOTGUN: BString = BString::str("Weapon_SportingShotgun");
pub const WEAPON_STAMPED_SMG: BString = BString::str("Weapon_StampedSMG");
pub const WEAPON_STANDARD_SUBMACHINE_GUN: BString = BString::str("Weapon_StandardSubmachineGun");
pub const WEAPON_STICK_GRENADE: BString = BString::str("Weapon_StickGrenade");
pub const WEAPON_SUBMACHINE_GUN: BString = BString::str("Weapon_SubmachineGun");
pub const WEAPON_SUPER_SHOTGUN: BString = BString::str("Weapon_SuperShotgun");
pub const WEAPON_SUPPRESSED_ASSAULT_RIFLE: BString = BString::str("Weapon_SuppressedAssaultRifle");
pub const WEAPON_SUPPRESSED_BULLPUP_SMG: BString = BString::str("Weapon_SuppressedBullpupSMG");
pub const WEAPON_SUPPRESSED_GUARD_PISTOL: BString = BString::str("Weapon_SuppressedGuardPistol");
pub const WEAPON_SUPPRESSED_HEAVY_SMG: BString = BString::str("Weapon_SuppressedHeavySMG");
pub const WEAPON_SUPPRESSED_MICRO_SMG: BString = BString::str("Weapon_SuppressedMicroSMG");
pub const WEAPON_SUPPRESSED_PISTOL: BString = BString::str("Weapon_SuppressedPistol");
pub const WEAPON_SUPPRESSED_SERVICE_RIFLE: BString = BString::str("Weapon_SuppressedServiceRifle");
pub const WEAPON_TACTICAL_SMG: BString = BString::str("Weapon_TacticalSMG");
pub const WEAPON_TACTICAL_SHOTGUN: BString = BString::str("Weapon_TacticalShotgun");
pub const WEAPON_TOMAHAWK: BString = BString::str("Weapon_Tomahawk");
pub const WEAPON_TWIN_CANNON: BString = BString::str("Weapon_TwinCannon");
pub const WEAPON_TYPEWRITER_SMG: BString = BString::str("Weapon_TypewriterSMG");
pub const WEAPON_ZWEIHANDER: BString = BString::str("Weapon_Zweihander");

pub const BR_ITEM_BASE_ASSETS: &[BString] = &[
    BP_ITEM_BASE,
    WEAPON_AP_CARBINE,
    WEAPON_ANTI_MATERIEL_RIFLE,
    WEAPON_ARMING_SWORD,
    WEAPON_ASSAULT_RIFLE,
    WEAPON_AUTO_SHOTGUN,
    WEAPON_BANDAGE,
    WEAPON_BATTLEAXE,
    WEAPON_BAZOOKA,
    WEAPON_BOLT_ACTION_RIFLE,
    WEAPON_BOW,
    WEAPON_BOX_PISTOL,
    WEAPON_BULLPUP_RIFLE,
    WEAPON_BULLPUP_SMG,
    WEAPON_CHARGED_LONGSWORD,
    WEAPON_CLAWS,
    WEAPON_COACH_GUN,
    WEAPON_CRYSTAL_KALIS,
    WEAPON_DERRINGER,
    WEAPON_DYNAMITE,
    WEAPON_FLINTLOCK_PISTOL,
    WEAPON_GRENADE_LAUNCHER,
    WEAPON_GUARD_PISTOL,
    WEAPON_HANDAXE,
    WEAPON_HEALTH_POTION,
    WEAPON_HEAVY_ASSAULT_RIFLE,
    WEAPON_HEAVY_SMG,
    WEAPON_HERO_SWORD,
    WEAPON_HIGH_POWER_PISTOL,
    WEAPON_HOLO_BLADE,
    WEAPON_HUNTING_SHOTGUN,
    WEAPON_IMPACT_GRENADE,
    WEAPON_IMPULSE_GRENADE,
    WEAPON_KNIFE,
    WEAPON_LASER_AXE,
    WEAPON_LASER_CLEAVER,
    WEAPON_LEVER_ACTION_RIFLE,
    WEAPON_LIGHT_MACHINE_GUN,
    WEAPON_LONGSWORD,
    WEAPON_MAGNUM_PISTOL,
    WEAPON_MEDI_SYRINGE,
    WEAPON_MICRO_SMG,
    WEAPON_MINIGUN,
    WEAPON_MISSILE_LAUNCHER,
    WEAPON_PDW,
    WEAPON_PICKAXE,
    WEAPON_PIPE_BOMB,
    WEAPON_PISTOL,
    WEAPON_PLASMA_PISTOL,
    WEAPON_PLASMA_SMG,
    WEAPON_PULSE_CARBINE,
    WEAPON_PULSE_RIFLE,
    WEAPON_QUAD_LAUNCHER,
    WEAPON_REVOLVER,
    WEAPON_ROAD_FLARE,
    WEAPON_ROCKET_JUMPER,
    WEAPON_ROCKET_LAUNCHER,
    WEAPON_SABRE,
    WEAPON_SEMI_AUTO_RIFLE,
    WEAPON_SERVICE_RIFLE,
    WEAPON_SHADOW_CLAWS,
    WEAPON_SHARP_CLAWS,
    WEAPON_SHOTGUN,
    WEAPON_SLUG_SHOTGUN,
    WEAPON_SMOKE_GRENADE,
    WEAPON_SNIPER,
    WEAPON_SODA_CAN,
    WEAPON_SPATHA,
    WEAPON_SPEAR,
    WEAPON_SPORTING_SHOTGUN,
    WEAPON_STAMPED_SMG,
    WEAPON_STANDARD_SUBMACHINE_GUN,
    WEAPON_STICK_GRENADE,
    WEAPON_SUBMACHINE_GUN,
    WEAPON_SUPER_SHOTGUN,
    WEAPON_SUPPRESSED_ASSAULT_RIFLE,
    WEAPON_SUPPRESSED_BULLPUP_SMG,
    WEAPON_SUPPRESSED_GUARD_PISTOL,
    WEAPON_SUPPRESSED_HEAVY_SMG,
    WEAPON_SUPPRESSED_MICRO_SMG,
    WEAPON_SUPPRESSED_PISTOL,
    WEAPON_SUPPRESSED_SERVICE_RIFLE,
    WEAPON_TACTICAL_SMG,
    WEAPON_TACTICAL_SHOTGUN,
    WEAPON_TOMAHAWK,
    WEAPON_TWIN_CANNON,
    WEAPON_TYPEWRITER_SMG,
    WEAPON_ZWEIHANDER,
];

// === BRPickupBase (99) ===
pub const BP_ITEM_PICKUP_AP_CARBINE: BString = BString::str("BP_ItemPickup_APCarbine");
pub const BP_ITEM_PICKUP_ANTI_MATERIEL_RIFLE: BString = BString::str("BP_ItemPickup_AntiMaterielRifle");
pub const BP_ITEM_PICKUP_ARMING_SWORD: BString = BString::str("BP_ItemPickup_ArmingSword");
pub const BP_ITEM_PICKUP_ASSAULT_RIFLE: BString = BString::str("BP_ItemPickup_AssaultRifle");
pub const BP_ITEM_PICKUP_AUTO_SHOTGUN: BString = BString::str("BP_ItemPickup_AutoShotgun");
pub const BP_ITEM_PICKUP_BANDAGE: BString = BString::str("BP_ItemPickup_Bandage");
pub const BP_ITEM_PICKUP_BASIC_CLAWS: BString = BString::str("BP_ItemPickup_BasicClaws");
pub const BP_ITEM_PICKUP_BATTLEAXE: BString = BString::str("BP_ItemPickup_Battleaxe");
pub const BP_ITEM_PICKUP_BAZOOKA: BString = BString::str("BP_ItemPickup_Bazooka");
pub const BP_ITEM_PICKUP_BOLT_ACTION_RIFLE: BString = BString::str("BP_ItemPickup_BoltActionRifle");
pub const BP_ITEM_PICKUP_BOW: BString = BString::str("BP_ItemPickup_Bow");
pub const BP_ITEM_PICKUP_BOX_PISTOL: BString = BString::str("BP_ItemPickup_BoxPistol");
pub const BP_ITEM_PICKUP_BULLPUP_RIFLE: BString = BString::str("BP_ItemPickup_BullpupRifle");
pub const BP_ITEM_PICKUP_BULLPUP_SMG: BString = BString::str("BP_ItemPickup_BullpupSMG");
pub const BP_ITEM_PICKUP_CHARGED_LONGSWORD: BString = BString::str("BP_ItemPickup_ChargedLongsword");
pub const BP_ITEM_PICKUP_CLAWS: BString = BString::str("BP_ItemPickup_Claws");
pub const BP_ITEM_PICKUP_CRYSTAL_KALIS: BString = BString::str("BP_ItemPickup_CrystalKalis");
pub const BP_ITEM_PICKUP_DERRINGER: BString = BString::str("BP_ItemPickup_Derringer");
pub const BP_ITEM_PICKUP_DYNAMITE: BString = BString::str("BP_ItemPickup_Dynamite");
pub const BP_ITEM_PICKUP_FLINTLOCK_PISTOL: BString = BString::str("BP_ItemPickup_Flintlock_Pistol");
pub const BP_ITEM_PICKUP_GRENADE_LAUNCHER: BString = BString::str("BP_ItemPickup_GrenadeLauncher");
pub const BP_ITEM_PICKUP_GUARD_PISTOL: BString = BString::str("BP_ItemPickup_GuardPistol");
pub const BP_ITEM_PICKUP_HANDAXE: BString = BString::str("BP_ItemPickup_Handaxe");
pub const BP_ITEM_PICKUP_HEALTH_POTION: BString = BString::str("BP_ItemPickup_HealthPotion");
pub const BP_ITEM_PICKUP_HEAVY_ASSAULT_RIFLE: BString = BString::str("BP_ItemPickup_HeavyAssaultRifle");
pub const BP_ITEM_PICKUP_HEAVY_SMG: BString = BString::str("BP_ItemPickup_HeavySMG");
pub const BP_ITEM_PICKUP_HERO_SWORD: BString = BString::str("BP_ItemPickup_HeroSword");
pub const BP_ITEM_PICKUP_HIGH_POWER_PISTOL: BString = BString::str("BP_ItemPickup_HighPowerPistol");
pub const BP_ITEM_PICKUP_HOLO_BLADE: BString = BString::str("BP_ItemPickup_HoloBlade");
pub const BP_ITEM_PICKUP_HUNTING_SHOTGUN: BString = BString::str("BP_ItemPickup_HuntingShotgun");
pub const BP_ITEM_PICKUP_IMPACT_GRENADE: BString = BString::str("BP_ItemPickup_ImpactGrenade");
pub const BP_ITEM_PICKUP_IMPULSE_GRENADE: BString = BString::str("BP_ItemPickup_ImpulseGrenade");
pub const BP_ITEM_PICKUP_KNIFE: BString = BString::str("BP_ItemPickup_Knife");
pub const BP_ITEM_PICKUP_LASER_AXE: BString = BString::str("BP_ItemPickup_LaserAxe");
pub const BP_ITEM_PICKUP_LASER_CLEAVER: BString = BString::str("BP_ItemPickup_LaserCleaver");
pub const BP_ITEM_PICKUP_LEVER_ACTION_RIFLE: BString = BString::str("BP_ItemPickup_LeverActionRifle");
pub const BP_ITEM_PICKUP_LIGHT_MACHINE_GUN: BString = BString::str("BP_ItemPickup_LightMachineGun");
pub const BP_ITEM_PICKUP_LONGSWORD: BString = BString::str("BP_ItemPickup_Longsword");
pub const BP_ITEM_PICKUP_MAGNUM_PISTOL: BString = BString::str("BP_ItemPickup_MagnumPistol");
pub const BP_ITEM_PICKUP_MEDI_SYRINGE: BString = BString::str("BP_ItemPickup_MediSyringe");
pub const BP_ITEM_PICKUP_MICRO_SMG: BString = BString::str("BP_ItemPickup_MicroSMG");
pub const BP_ITEM_PICKUP_MINIGUN: BString = BString::str("BP_ItemPickup_Minigun");
pub const BP_ITEM_PICKUP_MISSILE_LAUNCHER: BString = BString::str("BP_ItemPickup_MissileLauncher");
pub const BP_ITEM_PICKUP_PDW: BString = BString::str("BP_ItemPickup_PDW");
pub const BP_ITEM_PICKUP_PICKAXE: BString = BString::str("BP_ItemPickup_Pickaxe");
pub const BP_ITEM_PICKUP_PIPE_BOMB: BString = BString::str("BP_ItemPickup_PipeBomb");
pub const BP_ITEM_PICKUP_PISTOL: BString = BString::str("BP_ItemPickup_Pistol");
pub const BP_ITEM_PICKUP_PLASMA_PISTOL: BString = BString::str("BP_ItemPickup_PlasmaPistol");
pub const BP_ITEM_PICKUP_PLASMA_SMG: BString = BString::str("BP_ItemPickup_PlasmaSMG");
pub const BP_ITEM_PICKUP_PULSE_CARBINE: BString = BString::str("BP_ItemPickup_PulseCarbine");
pub const BP_ITEM_PICKUP_PULSE_RIFLE: BString = BString::str("BP_ItemPickup_PulseRifle");
pub const BP_ITEM_PICKUP_QUAD_LAUNCHER: BString = BString::str("BP_ItemPickup_QuadLauncher");
pub const BP_ITEM_PICKUP_REVOLVER: BString = BString::str("BP_ItemPickup_Revolver");
pub const BP_ITEM_PICKUP_ROAD_FLARE: BString = BString::str("BP_ItemPickup_RoadFlare");
pub const BP_ITEM_PICKUP_ROCKET_JUMPER: BString = BString::str("BP_ItemPickup_RocketJumper");
pub const BP_ITEM_PICKUP_ROCKET_LAUNCHER: BString = BString::str("BP_ItemPickup_RocketLauncher");
pub const BP_ITEM_PICKUP_SABRE: BString = BString::str("BP_ItemPickup_Sabre");
pub const BP_ITEM_PICKUP_SEMI_AUTO_RIFLE: BString = BString::str("BP_ItemPickup_SemiAutoRifle");
pub const BP_ITEM_PICKUP_SERVICE_RIFLE: BString = BString::str("BP_ItemPickup_ServiceRifle");
pub const BP_ITEM_PICKUP_SHADOW_CLAWS: BString = BString::str("BP_ItemPickup_ShadowClaws");
pub const BP_ITEM_PICKUP_SHOTGUN: BString = BString::str("BP_ItemPickup_Shotgun");
pub const BP_ITEM_PICKUP_SLUG_SHOTGUN: BString = BString::str("BP_ItemPickup_SlugShotgun");
pub const BP_ITEM_PICKUP_SMOKE_GRENADE: BString = BString::str("BP_ItemPickup_SmokeGrenade");
pub const BP_ITEM_PICKUP_SNIPER_RIFLE: BString = BString::str("BP_ItemPickup_SniperRifle");
pub const BP_ITEM_PICKUP_SODA: BString = BString::str("BP_ItemPickup_Soda");
pub const BP_ITEM_PICKUP_SPATHA: BString = BString::str("BP_ItemPickup_Spatha");
pub const BP_ITEM_PICKUP_SPEAR: BString = BString::str("BP_ItemPickup_Spear");
pub const BP_ITEM_PICKUP_SPORTING_SHOTGUN: BString = BString::str("BP_ItemPickup_SportingShotgun");
pub const BP_ITEM_PICKUP_STAMPED_SMG: BString = BString::str("BP_ItemPickup_StampedSMG");
pub const BP_ITEM_PICKUP_STICK_GRENADE: BString = BString::str("BP_ItemPickup_StickGrenade");
pub const BP_ITEM_PICKUP_SUBMACHINE_GUN: BString = BString::str("BP_ItemPickup_SubmachineGun");
pub const BP_ITEM_PICKUP_SUBMACHINE_GUN_UNSUPPRESSED: BString = BString::str("BP_ItemPickup_SubmachineGun_Unsuppressed");
pub const BP_ITEM_PICKUP_SUPER_SHOTGUN: BString = BString::str("BP_ItemPickup_SuperShotgun");
pub const BP_ITEM_PICKUP_SUPPRESSED_ASSAULT_RIFLE: BString = BString::str("BP_ItemPickup_SuppressedAssaultRifle");
pub const BP_ITEM_PICKUP_SUPPRESSED_BULLPUP_SMG: BString = BString::str("BP_ItemPickup_SuppressedBullpupSMG");
pub const BP_ITEM_PICKUP_SUPPRESSED_GUARD_PISTOL: BString = BString::str("BP_ItemPickup_SuppressedGuardPistol");
pub const BP_ITEM_PICKUP_SUPPRESSED_HEAVY_SMG: BString = BString::str("BP_ItemPickup_SuppressedHeavySMG");
pub const BP_ITEM_PICKUP_SUPPRESSED_MICRO_SMG: BString = BString::str("BP_ItemPickup_SuppressedMicroSMG");
pub const BP_ITEM_PICKUP_SUPPRESSED_PISTOL: BString = BString::str("BP_ItemPickup_SuppressedPistol");
pub const BP_ITEM_PICKUP_SUPPRESSED_SERVICE_R_IFLE: BString = BString::str("BP_ItemPickup_SuppressedServiceRIfle");
pub const BP_ITEM_PICKUP_TACTICAL_SMG: BString = BString::str("BP_ItemPickup_TacticalSMG");
pub const BP_ITEM_PICKUP_TACTICAL_SHOTGUN: BString = BString::str("BP_ItemPickup_TacticalShotgun");
pub const BP_ITEM_PICKUP_TOMAHAWK: BString = BString::str("BP_ItemPickup_Tomahawk");
pub const BP_ITEM_PICKUP_TWIN_CANNON: BString = BString::str("BP_ItemPickup_TwinCannon");
pub const BP_ITEM_PICKUP_TYPEWRITER_SMG: BString = BString::str("BP_ItemPickup_TypewriterSMG");
pub const BP_ITEM_PICKUP_ZWEIHANDER: BString = BString::str("BP_ItemPickup_Zweihander");
pub const BP_PICKUP_AMMO_ARROWS: BString = BString::str("BP_Pickup_Ammo_Arrows");
pub const BP_PICKUP_AMMO_BLACK_POWDER: BString = BString::str("BP_Pickup_Ammo_BlackPowder");
pub const BP_PICKUP_AMMO_EXPLOSIVE: BString = BString::str("BP_Pickup_Ammo_Explosive");
pub const BP_PICKUP_AMMO_HEAVY: BString = BString::str("BP_Pickup_Ammo_Heavy");
pub const BP_PICKUP_AMMO_LIGHT: BString = BString::str("BP_Pickup_Ammo_Light");
pub const BP_PICKUP_AMMO_MAGNUM: BString = BString::str("BP_Pickup_Ammo_Magnum");
pub const BP_PICKUP_AMMO_MEDIUM: BString = BString::str("BP_Pickup_Ammo_Medium");
pub const BP_PICKUP_AMMO_PLASMA: BString = BString::str("BP_Pickup_Ammo_Plasma");
pub const BP_PICKUP_AMMO_PULSE: BString = BString::str("BP_Pickup_Ammo_Pulse");
pub const BP_PICKUP_AMMO_SHOTGUN: BString = BString::str("BP_Pickup_Ammo_Shotgun");
pub const BP_PICKUP_HEALTH_LARGE: BString = BString::str("BP_Pickup_Health_Large");
pub const BP_PICKUP_HEALTH_MEDIUM: BString = BString::str("BP_Pickup_Health_Medium");
pub const BP_PICKUP_HEALTH_SMALL: BString = BString::str("BP_Pickup_Health_Small");

pub const BR_PICKUP_BASE_ASSETS: &[BString] = &[
    BP_ITEM_PICKUP_AP_CARBINE,
    BP_ITEM_PICKUP_ANTI_MATERIEL_RIFLE,
    BP_ITEM_PICKUP_ARMING_SWORD,
    BP_ITEM_PICKUP_ASSAULT_RIFLE,
    BP_ITEM_PICKUP_AUTO_SHOTGUN,
    BP_ITEM_PICKUP_BANDAGE,
    BP_ITEM_PICKUP_BASIC_CLAWS,
    BP_ITEM_PICKUP_BATTLEAXE,
    BP_ITEM_PICKUP_BAZOOKA,
    BP_ITEM_PICKUP_BOLT_ACTION_RIFLE,
    BP_ITEM_PICKUP_BOW,
    BP_ITEM_PICKUP_BOX_PISTOL,
    BP_ITEM_PICKUP_BULLPUP_RIFLE,
    BP_ITEM_PICKUP_BULLPUP_SMG,
    BP_ITEM_PICKUP_CHARGED_LONGSWORD,
    BP_ITEM_PICKUP_CLAWS,
    BP_ITEM_PICKUP_CRYSTAL_KALIS,
    BP_ITEM_PICKUP_DERRINGER,
    BP_ITEM_PICKUP_DYNAMITE,
    BP_ITEM_PICKUP_FLINTLOCK_PISTOL,
    BP_ITEM_PICKUP_GRENADE_LAUNCHER,
    BP_ITEM_PICKUP_GUARD_PISTOL,
    BP_ITEM_PICKUP_HANDAXE,
    BP_ITEM_PICKUP_HEALTH_POTION,
    BP_ITEM_PICKUP_HEAVY_ASSAULT_RIFLE,
    BP_ITEM_PICKUP_HEAVY_SMG,
    BP_ITEM_PICKUP_HERO_SWORD,
    BP_ITEM_PICKUP_HIGH_POWER_PISTOL,
    BP_ITEM_PICKUP_HOLO_BLADE,
    BP_ITEM_PICKUP_HUNTING_SHOTGUN,
    BP_ITEM_PICKUP_IMPACT_GRENADE,
    BP_ITEM_PICKUP_IMPULSE_GRENADE,
    BP_ITEM_PICKUP_KNIFE,
    BP_ITEM_PICKUP_LASER_AXE,
    BP_ITEM_PICKUP_LASER_CLEAVER,
    BP_ITEM_PICKUP_LEVER_ACTION_RIFLE,
    BP_ITEM_PICKUP_LIGHT_MACHINE_GUN,
    BP_ITEM_PICKUP_LONGSWORD,
    BP_ITEM_PICKUP_MAGNUM_PISTOL,
    BP_ITEM_PICKUP_MEDI_SYRINGE,
    BP_ITEM_PICKUP_MICRO_SMG,
    BP_ITEM_PICKUP_MINIGUN,
    BP_ITEM_PICKUP_MISSILE_LAUNCHER,
    BP_ITEM_PICKUP_PDW,
    BP_ITEM_PICKUP_PICKAXE,
    BP_ITEM_PICKUP_PIPE_BOMB,
    BP_ITEM_PICKUP_PISTOL,
    BP_ITEM_PICKUP_PLASMA_PISTOL,
    BP_ITEM_PICKUP_PLASMA_SMG,
    BP_ITEM_PICKUP_PULSE_CARBINE,
    BP_ITEM_PICKUP_PULSE_RIFLE,
    BP_ITEM_PICKUP_QUAD_LAUNCHER,
    BP_ITEM_PICKUP_REVOLVER,
    BP_ITEM_PICKUP_ROAD_FLARE,
    BP_ITEM_PICKUP_ROCKET_JUMPER,
    BP_ITEM_PICKUP_ROCKET_LAUNCHER,
    BP_ITEM_PICKUP_SABRE,
    BP_ITEM_PICKUP_SEMI_AUTO_RIFLE,
    BP_ITEM_PICKUP_SERVICE_RIFLE,
    BP_ITEM_PICKUP_SHADOW_CLAWS,
    BP_ITEM_PICKUP_SHOTGUN,
    BP_ITEM_PICKUP_SLUG_SHOTGUN,
    BP_ITEM_PICKUP_SMOKE_GRENADE,
    BP_ITEM_PICKUP_SNIPER_RIFLE,
    BP_ITEM_PICKUP_SODA,
    BP_ITEM_PICKUP_SPATHA,
    BP_ITEM_PICKUP_SPEAR,
    BP_ITEM_PICKUP_SPORTING_SHOTGUN,
    BP_ITEM_PICKUP_STAMPED_SMG,
    BP_ITEM_PICKUP_STICK_GRENADE,
    BP_ITEM_PICKUP_SUBMACHINE_GUN,
    BP_ITEM_PICKUP_SUBMACHINE_GUN_UNSUPPRESSED,
    BP_ITEM_PICKUP_SUPER_SHOTGUN,
    BP_ITEM_PICKUP_SUPPRESSED_ASSAULT_RIFLE,
    BP_ITEM_PICKUP_SUPPRESSED_BULLPUP_SMG,
    BP_ITEM_PICKUP_SUPPRESSED_GUARD_PISTOL,
    BP_ITEM_PICKUP_SUPPRESSED_HEAVY_SMG,
    BP_ITEM_PICKUP_SUPPRESSED_MICRO_SMG,
    BP_ITEM_PICKUP_SUPPRESSED_PISTOL,
    BP_ITEM_PICKUP_SUPPRESSED_SERVICE_R_IFLE,
    BP_ITEM_PICKUP_TACTICAL_SMG,
    BP_ITEM_PICKUP_TACTICAL_SHOTGUN,
    BP_ITEM_PICKUP_TOMAHAWK,
    BP_ITEM_PICKUP_TWIN_CANNON,
    BP_ITEM_PICKUP_TYPEWRITER_SMG,
    BP_ITEM_PICKUP_ZWEIHANDER,
    BP_PICKUP_AMMO_ARROWS,
    BP_PICKUP_AMMO_BLACK_POWDER,
    BP_PICKUP_AMMO_EXPLOSIVE,
    BP_PICKUP_AMMO_HEAVY,
    BP_PICKUP_AMMO_LIGHT,
    BP_PICKUP_AMMO_MAGNUM,
    BP_PICKUP_AMMO_MEDIUM,
    BP_PICKUP_AMMO_PLASMA,
    BP_PICKUP_AMMO_PULSE,
    BP_PICKUP_AMMO_SHOTGUN,
    BP_PICKUP_HEALTH_LARGE,
    BP_PICKUP_HEALTH_MEDIUM,
    BP_PICKUP_HEALTH_SMALL,
];

// === BRWeaponProjectile (69) ===
pub const BP_BULLET_PROJECTILE: BString = BString::str("BP_Bullet_Projectile");
pub const PROJECTILE_AMR: BString = BString::str("Projectile_AMR");
pub const PROJECTILE_AP_CARBINE: BString = BString::str("Projectile_APCarbine");
pub const PROJECTILE_ASSAULT_RIFLE: BString = BString::str("Projectile_AssaultRifle");
pub const PROJECTILE_AUTO_SHOTGUN: BString = BString::str("Projectile_AutoShotgun");
pub const PROJECTILE_BAZOOKA: BString = BString::str("Projectile_Bazooka");
pub const PROJECTILE_BOLT_ACTION_RIFLE: BString = BString::str("Projectile_BoltActionRifle");
pub const PROJECTILE_BOW_CHARGED: BString = BString::str("Projectile_Bow_Charged");
pub const PROJECTILE_BOW_HALF_CHARGED: BString = BString::str("Projectile_Bow_HalfCharged");
pub const PROJECTILE_BOW_UNCHARGED: BString = BString::str("Projectile_Bow_Uncharged");
pub const PROJECTILE_BOX_PISTOL: BString = BString::str("Projectile_BoxPistol");
pub const PROJECTILE_BULLPUP_RIFLE: BString = BString::str("Projectile_BullpupRifle");
pub const PROJECTILE_BULLPUP_SMG: BString = BString::str("Projectile_BullpupSMG");
pub const PROJECTILE_DERRINGER: BString = BString::str("Projectile_Derringer");
pub const PROJECTILE_DYNAMITE: BString = BString::str("Projectile_Dynamite");
pub const PROJECTILE_FLINTLOCK_PISTOL: BString = BString::str("Projectile_Flintlock_Pistol");
pub const PROJECTILE_GRENADE_LAUNCHER: BString = BString::str("Projectile_GrenadeLauncher");
pub const PROJECTILE_GUARD_PISTOL: BString = BString::str("Projectile_GuardPistol");
pub const PROJECTILE_HANDAXE: BString = BString::str("Projectile_Handaxe");
pub const PROJECTILE_HEAVY_ASSAULT_RIFLE: BString = BString::str("Projectile_HeavyAssaultRifle");
pub const PROJECTILE_HEAVY_SMG: BString = BString::str("Projectile_HeavySMG");
pub const PROJECTILE_HIGH_POWER_PISTOL: BString = BString::str("Projectile_HighPowerPistol");
pub const PROJECTILE_HUNTING_SHOTGUN: BString = BString::str("Projectile_HuntingShotgun");
pub const PROJECTILE_IMPACT_GRENADE: BString = BString::str("Projectile_ImpactGrenade");
pub const PROJECTILE_IMPULSE_GRENADE: BString = BString::str("Projectile_ImpulseGrenade");
pub const PROJECTILE_LEVER_ACTION_RIFLE: BString = BString::str("Projectile_LeverActionRifle");
pub const PROJECTILE_LIGHT_MACHINE_GUN: BString = BString::str("Projectile_LightMachineGun");
pub const PROJECTILE_MAGNUM_PISTOL: BString = BString::str("Projectile_MagnumPistol");
pub const PROJECTILE_MICRO_SMG: BString = BString::str("Projectile_MicroSMG");
pub const PROJECTILE_MINIGUN: BString = BString::str("Projectile_Minigun");
pub const PROJECTILE_PDW: BString = BString::str("Projectile_PDW");
pub const PROJECTILE_PIPE_BOMB: BString = BString::str("Projectile_PipeBomb");
pub const PROJECTILE_PISTOL: BString = BString::str("Projectile_Pistol");
pub const PROJECTILE_PLASMA_PISTOL: BString = BString::str("Projectile_PlasmaPistol");
pub const PROJECTILE_PLASMA_SMG: BString = BString::str("Projectile_PlasmaSMG");
pub const PROJECTILE_PULSE_CARBINE: BString = BString::str("Projectile_PulseCarbine");
pub const PROJECTILE_PULSE_RIFLE: BString = BString::str("Projectile_PulseRifle");
pub const PROJECTILE_PULSE_RIFLE_ROCKET: BString = BString::str("Projectile_PulseRifle_Rocket");
pub const PROJECTILE_QUAD_LAUNCHER: BString = BString::str("Projectile_QuadLauncher");
pub const PROJECTILE_REVOLVER_NEW: BString = BString::str("Projectile_Revolver_New");
pub const PROJECTILE_REVOLVER_NO_HEADSHOT: BString = BString::str("Projectile_Revolver_NoHeadshot");
pub const PROJECTILE_ROAD_FLARE: BString = BString::str("Projectile_RoadFlare");
pub const PROJECTILE_ROCKET_JUMPER: BString = BString::str("Projectile_RocketJumper");
pub const PROJECTILE_ROCKET_LAUNCHER: BString = BString::str("Projectile_RocketLauncher");
pub const PROJECTILE_SEEKER_MISSILE: BString = BString::str("Projectile_SeekerMissile");
pub const PROJECTILE_SEMI_AUTO_RIFLE: BString = BString::str("Projectile_SemiAutoRifle");
pub const PROJECTILE_SERVICE_RIFLE: BString = BString::str("Projectile_ServiceRifle");
pub const PROJECTILE_SHOTGUN: BString = BString::str("Projectile_Shotgun");
pub const PROJECTILE_SLUG_SHOTGUN: BString = BString::str("Projectile_SlugShotgun");
pub const PROJECTILE_SMOKE_GRENADE_NEW: BString = BString::str("Projectile_SmokeGrenade_New");
pub const PROJECTILE_SNIPER: BString = BString::str("Projectile_Sniper");
pub const PROJECTILE_SPORTING_SHOTGUN: BString = BString::str("Projectile_SportingShotgun");
pub const PROJECTILE_STAMPED_SMG: BString = BString::str("Projectile_StampedSMG");
pub const PROJECTILE_STICK_GRENADE: BString = BString::str("Projectile_StickGrenade");
pub const PROJECTILE_SUBMACHINE_GUN: BString = BString::str("Projectile_SubmachineGun");
pub const PROJECTILE_SUBMACHINE_GUN_UNSUPPRESSED: BString = BString::str("Projectile_SubmachineGun_Unsuppressed");
pub const PROJECTILE_SUPER_SHOTGUN: BString = BString::str("Projectile_SuperShotgun");
pub const PROJECTILE_SUPPRESSED_ASSAULT_RIFLE: BString = BString::str("Projectile_SuppressedAssaultRifle");
pub const PROJECTILE_SUPPRESSED_BULLPUP_SMG: BString = BString::str("Projectile_SuppressedBullpupSMG");
pub const PROJECTILE_SUPPRESSED_GUARD_PISTOL: BString = BString::str("Projectile_SuppressedGuardPistol");
pub const PROJECTILE_SUPPRESSED_HEAVY_SMG: BString = BString::str("Projectile_SuppressedHeavySMG");
pub const PROJECTILE_SUPPRESSED_MICRO_SMG: BString = BString::str("Projectile_SuppressedMicroSMG");
pub const PROJECTILE_SUPPRESSED_PISTOL: BString = BString::str("Projectile_SuppressedPistol");
pub const PROJECTILE_SUPPRESSED_SERVICE_RIFLE: BString = BString::str("Projectile_SuppressedServiceRifle");
pub const PROJECTILE_TACTICAL_SMG: BString = BString::str("Projectile_TacticalSMG");
pub const PROJECTILE_TACTICAL_SHOTGUN: BString = BString::str("Projectile_TacticalShotgun");
pub const PROJECTILE_TOMAHAWK: BString = BString::str("Projectile_Tomahawk");
pub const PROJECTILE_TWIN_CANNON: BString = BString::str("Projectile_TwinCannon");
pub const PROJECTILE_TYPEWRITER_SMG: BString = BString::str("Projectile_TypewriterSMG");

pub const BR_WEAPON_PROJECTILE_ASSETS: &[BString] = &[
    BP_BULLET_PROJECTILE,
    PROJECTILE_AMR,
    PROJECTILE_AP_CARBINE,
    PROJECTILE_ASSAULT_RIFLE,
    PROJECTILE_AUTO_SHOTGUN,
    PROJECTILE_BAZOOKA,
    PROJECTILE_BOLT_ACTION_RIFLE,
    PROJECTILE_BOW_CHARGED,
    PROJECTILE_BOW_HALF_CHARGED,
    PROJECTILE_BOW_UNCHARGED,
    PROJECTILE_BOX_PISTOL,
    PROJECTILE_BULLPUP_RIFLE,
    PROJECTILE_BULLPUP_SMG,
    PROJECTILE_DERRINGER,
    PROJECTILE_DYNAMITE,
    PROJECTILE_FLINTLOCK_PISTOL,
    PROJECTILE_GRENADE_LAUNCHER,
    PROJECTILE_GUARD_PISTOL,
    PROJECTILE_HANDAXE,
    PROJECTILE_HEAVY_ASSAULT_RIFLE,
    PROJECTILE_HEAVY_SMG,
    PROJECTILE_HIGH_POWER_PISTOL,
    PROJECTILE_HUNTING_SHOTGUN,
    PROJECTILE_IMPACT_GRENADE,
    PROJECTILE_IMPULSE_GRENADE,
    PROJECTILE_LEVER_ACTION_RIFLE,
    PROJECTILE_LIGHT_MACHINE_GUN,
    PROJECTILE_MAGNUM_PISTOL,
    PROJECTILE_MICRO_SMG,
    PROJECTILE_MINIGUN,
    PROJECTILE_PDW,
    PROJECTILE_PIPE_BOMB,
    PROJECTILE_PISTOL,
    PROJECTILE_PLASMA_PISTOL,
    PROJECTILE_PLASMA_SMG,
    PROJECTILE_PULSE_CARBINE,
    PROJECTILE_PULSE_RIFLE,
    PROJECTILE_PULSE_RIFLE_ROCKET,
    PROJECTILE_QUAD_LAUNCHER,
    PROJECTILE_REVOLVER_NEW,
    PROJECTILE_REVOLVER_NO_HEADSHOT,
    PROJECTILE_ROAD_FLARE,
    PROJECTILE_ROCKET_JUMPER,
    PROJECTILE_ROCKET_LAUNCHER,
    PROJECTILE_SEEKER_MISSILE,
    PROJECTILE_SEMI_AUTO_RIFLE,
    PROJECTILE_SERVICE_RIFLE,
    PROJECTILE_SHOTGUN,
    PROJECTILE_SLUG_SHOTGUN,
    PROJECTILE_SMOKE_GRENADE_NEW,
    PROJECTILE_SNIPER,
    PROJECTILE_SPORTING_SHOTGUN,
    PROJECTILE_STAMPED_SMG,
    PROJECTILE_STICK_GRENADE,
    PROJECTILE_SUBMACHINE_GUN,
    PROJECTILE_SUBMACHINE_GUN_UNSUPPRESSED,
    PROJECTILE_SUPER_SHOTGUN,
    PROJECTILE_SUPPRESSED_ASSAULT_RIFLE,
    PROJECTILE_SUPPRESSED_BULLPUP_SMG,
    PROJECTILE_SUPPRESSED_GUARD_PISTOL,
    PROJECTILE_SUPPRESSED_HEAVY_SMG,
    PROJECTILE_SUPPRESSED_MICRO_SMG,
    PROJECTILE_SUPPRESSED_PISTOL,
    PROJECTILE_SUPPRESSED_SERVICE_RIFLE,
    PROJECTILE_TACTICAL_SMG,
    PROJECTILE_TACTICAL_SHOTGUN,
    PROJECTILE_TOMAHAWK,
    PROJECTILE_TWIN_CANNON,
    PROJECTILE_TYPEWRITER_SMG,
];

// === BrickAudioDescriptor (199) ===
pub const BA_AMB_ABSTRACT_SUBTLE_INTERFERENCE: BString = BString::str("BA_AMB_Abstract_Subtle_Interference");
pub const BA_AMB_COMPONENT_AIR_CONDITIONING_BUZZY_1: BString = BString::str("BA_AMB_Component_Air_Conditioning_Buzzy_1");
pub const BA_AMB_COMPONENT_AIR_CONDITIONING_BUZZY_2: BString = BString::str("BA_AMB_Component_Air_Conditioning_Buzzy_2");
pub const BA_AMB_COMPONENT_AIR_CONDITIONING_GRUNGY: BString = BString::str("BA_AMB_Component_Air_Conditioning_Grungy");
pub const BA_AMB_COMPONENT_AIR_CONDITIONING_WOBBLY: BString = BString::str("BA_AMB_Component_Air_Conditioning_Wobbly");
pub const BA_AMB_COMPONENT_ALARM_SCIFI_CREEPY: BString = BString::str("BA_AMB_Component_Alarm_Scifi_Creepy");
pub const BA_AMB_COMPONENT_ALARM_SCIFI_WARNING_1: BString = BString::str("BA_AMB_Component_Alarm_Scifi_Warning_1");
pub const BA_AMB_COMPONENT_ALARM_SCIFI_WARNING_2: BString = BString::str("BA_AMB_Component_Alarm_Scifi_Warning_2");
pub const BA_AMB_COMPONENT_ALARM_SCIFI_WARNING_3: BString = BString::str("BA_AMB_Component_Alarm_Scifi_Warning_3");
pub const BA_AMB_COMPONENT_AUTOMATED_VENDING: BString = BString::str("BA_AMB_Component_Automated_Vending");
pub const BA_AMB_COMPONENT_FIRES_FIREPLACE_1: BString = BString::str("BA_AMB_Component_Fires_Fireplace_1");
pub const BA_AMB_COMPONENT_HORN_CAR_GENERIC: BString = BString::str("BA_AMB_Component_Horn_Car_Generic");
pub const BA_AMB_COMPONENT_HORN_CAR_SMALL: BString = BString::str("BA_AMB_Component_Horn_Car_Small");
pub const BA_AMB_COMPONENT_HORN_CAR_TRUCK: BString = BString::str("BA_AMB_Component_Horn_Car_Truck");
pub const BA_AMB_COMPONENT_HOSPITAL_MISC_RESPIRATOR: BString = BString::str("BA_AMB_Component_Hospital_Misc_Respirator");
pub const BA_AMB_COMPONENT_HOSPITAL_MONITORS_HEART_1: BString = BString::str("BA_AMB_Component_Hospital_Monitors_Heart_1");
pub const BA_AMB_COMPONENT_HOSPITAL_MONITORS_HEART_2: BString = BString::str("BA_AMB_Component_Hospital_Monitors_Heart_2");
pub const BA_AMB_COMPONENT_HOSPITAL_MONITORS_HEART_3: BString = BString::str("BA_AMB_Component_Hospital_Monitors_Heart_3");
pub const BA_AMB_EXTERIOR_CITY: BString = BString::str("BA_AMB_Exterior_City");
pub const BA_AMB_EXTERIOR_CONSTRUCTION_HEAVY: BString = BString::str("BA_AMB_Exterior_Construction_Heavy");
pub const BA_AMB_EXTERIOR_CONSTRUCTION_LIGHT: BString = BString::str("BA_AMB_Exterior_Construction_Light");
pub const BA_AMB_EXTERIOR_COURTYARD: BString = BString::str("BA_AMB_Exterior_Courtyard");
pub const BA_AMB_EXTERIOR_GENTLE_FOREST: BString = BString::str("BA_AMB_Exterior_GentleForest");
pub const BA_AMB_EXTERIOR_NIGHT_CRICKETS: BString = BString::str("BA_AMB_Exterior_NightCrickets");
pub const BA_AMB_EXTERIOR_NOISY_FOREST: BString = BString::str("BA_AMB_Exterior_NoisyForest");
pub const BA_AMB_EXTERIOR_WINDY_FOREST: BString = BString::str("BA_AMB_Exterior_WindyForest");
pub const BA_AMB_EXTERIOR_WINDY_MOUNTAIN: BString = BString::str("BA_AMB_Exterior_WindyMountain");
pub const BA_AMB_INTERIOR_AIRCRAFT_CABIN_GENTLE: BString = BString::str("BA_AMB_Interior_Aircraft_Cabin_Gentle");
pub const BA_AMB_INTERIOR_AIRCRAFT_CABIN_INTENSE: BString = BString::str("BA_AMB_Interior_Aircraft_Cabin_Intense");
pub const BA_AMB_INTERIOR_DRIPPY_TUNNEL: BString = BString::str("BA_AMB_Interior_DrippyTunnel");
pub const BA_AMB_INTERIOR_ELECTRIC: BString = BString::str("BA_AMB_Interior_Electric");
pub const BA_AMB_INTERIOR_ELEVATOR_SHAFT: BString = BString::str("BA_AMB_Interior_Elevator_Shaft");
pub const BA_AMB_INTERIOR_LOW_FREQUENCY: BString = BString::str("BA_AMB_Interior_Low_Frequency");
pub const BA_AMB_INTERIOR_QUIET_AIRCONDITIONING: BString = BString::str("BA_AMB_Interior_Quiet_Airconditioning");
pub const BA_AMB_INTERIOR_SERVER_ROOM: BString = BString::str("BA_AMB_Interior_ServerRoom");
pub const BA_AMB_INTERIOR_SPACE_TUNNEL: BString = BString::str("BA_AMB_Interior_SpaceTunnel");
pub const BA_AMB_INTERIOR_UNDERWATER: BString = BString::str("BA_AMB_Interior_Underwater");
pub const BA_AIR_RAID_SIREN1: BString = BString::str("BA_AirRaidSiren1");
pub const BA_ALARMS_HOUSEHOLD_ALARM_CLOCK: BString = BString::str("BA_Alarms_Household_Alarm_Clock");
pub const BA_ALARMS_HOUSEHOLD_BELLS: BString = BString::str("BA_Alarms_Household_Bells");
pub const BA_ALARMS_HOUSEHOLD_BURGLAR: BString = BString::str("BA_Alarms_Household_Burglar");
pub const BA_ALARMS_HOUSEHOLD_CAR: BString = BString::str("BA_Alarms_Household_Car");
pub const BA_ALARMS_HOUSEHOLD_SMOKE: BString = BString::str("BA_Alarms_Household_Smoke");
pub const BA_ALARMS_HOUSEHOLD_WATCH_FAST: BString = BString::str("BA_Alarms_Household_Watch_Fast");
pub const BA_ALARMS_HOUSEHOLD_WATCH_SLOW: BString = BString::str("BA_Alarms_Household_Watch_Slow");
pub const BA_ALARMS_INDUSTRIAL_BELL: BString = BString::str("BA_Alarms_Industrial_Bell");
pub const BA_ALARMS_INDUSTRIAL_SECURITY: BString = BString::str("BA_Alarms_Industrial_Security");
pub const BA_ALARMS_INDUSTRIAL_TRUCK: BString = BString::str("BA_Alarms_Industrial_Truck");
pub const BA_CREAKING_METAL_SQUEAKY: BString = BString::str("BA_Creaking_Metal_Squeaky");
pub const BA_CREAKING_METAL_STRAINING: BString = BString::str("BA_Creaking_Metal_Straining");
pub const BA_CREAKING_METAL_STRESS: BString = BString::str("BA_Creaking_Metal_Stress");
pub const BA_CREAKING_WOOD_CONSTANT_RATTLING: BString = BString::str("BA_Creaking_Wood_Constant_Rattling");
pub const BA_CREAKING_WOOD_INTERIOR: BString = BString::str("BA_Creaking_Wood_Interior");
pub const BA_CREAKING_WOOD_MASSIVE: BString = BString::str("BA_Creaking_Wood_Massive");
pub const BA_CREAKING_WOOD_WAVING: BString = BString::str("BA_Creaking_Wood_Waving");
pub const BA_DEEP_MACHINE: BString = BString::str("BA_Deep_Machine");
pub const BA_ELECTRIC_MOTOR_1: BString = BString::str("BA_Electric_Motor_1");
pub const BA_FAUNA_BIRDS_ALDER_FLYCATCHER: BString = BString::str("BA_Fauna_Birds_AlderFlycatcher");
pub const BA_FAUNA_BIRDS_MIXED: BString = BString::str("BA_Fauna_Birds_Mixed");
pub const BA_FAUNA_BIRDS_NIGHTINGALE: BString = BString::str("BA_Fauna_Birds_Nightingale");
pub const BA_JACOBS_LADDER: BString = BString::str("BA_Jacobs_Ladder");
pub const BA_JACUZZI: BString = BString::str("BA_Jacuzzi");
pub const BA_KITCHEN_DISHES: BString = BString::str("BA_Kitchen_Dishes");
pub const BA_KITCHEN_DISHWASHER_COLLECTING_WATER: BString = BString::str("BA_Kitchen_Dishwasher_Collecting_Water");
pub const BA_KITCHEN_DISHWASHER_RUNNING: BString = BString::str("BA_Kitchen_Dishwasher_Running");
pub const BA_KITCHEN_FRYING_FOOD_LARGE: BString = BString::str("BA_Kitchen_Frying_Food_Large");
pub const BA_KITCHEN_FRYING_FOOD_SMALL: BString = BString::str("BA_Kitchen_Frying_Food_Small");
pub const BA_MUS_COMPONENT_APX_ALLEGRO: BString = BString::str("BA_MUS_Component_APX_Allegro");
pub const BA_MUS_COMPONENT_APX_APOGEE: BString = BString::str("BA_MUS_Component_APX_Apogee");
pub const BA_MUS_COMPONENT_APX_ARCADIA: BString = BString::str("BA_MUS_Component_APX_Arcadia");
pub const BA_MUS_COMPONENT_APX_ARENA: BString = BString::str("BA_MUS_Component_APX_Arena");
pub const BA_MUS_COMPONENT_APX_CANOPY_OF_LIGHT: BString = BString::str("BA_MUS_Component_APX_Canopy_of_Light");
pub const BA_MUS_COMPONENT_APX_CARRIER: BString = BString::str("BA_MUS_Component_APX_Carrier");
pub const BA_MUS_COMPONENT_APX_CLOCKWORK: BString = BString::str("BA_MUS_Component_APX_Clockwork");
pub const BA_MUS_COMPONENT_APX_CRYPT: BString = BString::str("BA_MUS_Component_APX_Crypt");
pub const BA_MUS_COMPONENT_APX_ELEGANT: BString = BString::str("BA_MUS_Component_APX_Elegant");
pub const BA_MUS_COMPONENT_APX_ENCHANTMENT: BString = BString::str("BA_MUS_Component_APX_Enchantment");
pub const BA_MUS_COMPONENT_APX_EXPLORERS: BString = BString::str("BA_MUS_Component_APX_Explorers");
pub const BA_MUS_COMPONENT_APX_FROG: BString = BString::str("BA_MUS_Component_APX_Frog");
pub const BA_MUS_COMPONENT_APX_FUSION: BString = BString::str("BA_MUS_Component_APX_Fusion");
pub const BA_MUS_COMPONENT_APX_LA_ROSA: BString = BString::str("BA_MUS_Component_APX_LaRosa");
pub const BA_MUS_COMPONENT_APX_LUX: BString = BString::str("BA_MUS_Component_APX_Lux");
pub const BA_MUS_COMPONENT_APX_MAINFRAME: BString = BString::str("BA_MUS_Component_APX_Mainframe");
pub const BA_MUS_COMPONENT_APX_MAJESTIC: BString = BString::str("BA_MUS_Component_APX_Majestic");
pub const BA_MUS_COMPONENT_APX_MELLOW: BString = BString::str("BA_MUS_Component_APX_Mellow");
pub const BA_MUS_COMPONENT_APX_MICRO: BString = BString::str("BA_MUS_Component_APX_Micro");
pub const BA_MUS_COMPONENT_APX_MISSION: BString = BString::str("BA_MUS_Component_APX_Mission");
pub const BA_MUS_COMPONENT_APX_MOMENT: BString = BString::str("BA_MUS_Component_APX_Moment");
pub const BA_MUS_COMPONENT_APX_MOOD: BString = BString::str("BA_MUS_Component_APX_Mood");
pub const BA_MUS_COMPONENT_APX_MUSICBOX: BString = BString::str("BA_MUS_Component_APX_Musicbox");
pub const BA_MUS_COMPONENT_APX_NOIR: BString = BString::str("BA_MUS_Component_APX_Noir");
pub const BA_MUS_COMPONENT_APX_OASIS: BString = BString::str("BA_MUS_Component_APX_Oasis");
pub const BA_MUS_COMPONENT_APX_OPEN_RANGE: BString = BString::str("BA_MUS_Component_APX_OpenRange");
pub const BA_MUS_COMPONENT_APX_PULSE: BString = BString::str("BA_MUS_Component_APX_Pulse");
pub const BA_MUS_COMPONENT_APX_REFRACTION: BString = BString::str("BA_MUS_Component_APX_Refraction");
pub const BA_MUS_COMPONENT_APX_SANCTUARY: BString = BString::str("BA_MUS_Component_APX_Sanctuary");
pub const BA_MUS_COMPONENT_APX_SERENITY: BString = BString::str("BA_MUS_Component_APX_Serenity");
pub const BA_MUS_COMPONENT_APX_SET_SAIL: BString = BString::str("BA_MUS_Component_APX_SetSail");
pub const BA_MUS_COMPONENT_APX_SHADOW: BString = BString::str("BA_MUS_Component_APX_Shadow");
pub const BA_MUS_COMPONENT_APX_SPIES: BString = BString::str("BA_MUS_Component_APX_Spies");
pub const BA_MUS_COMPONENT_APX_STANCED: BString = BString::str("BA_MUS_Component_APX_Stanced");
pub const BA_MUS_COMPONENT_APX_STROLL: BString = BString::str("BA_MUS_Component_APX_Stroll");
pub const BA_MUS_COMPONENT_APX_TESTAROSSA: BString = BString::str("BA_MUS_Component_APX_Testarossa");
pub const BA_MUS_COMPONENT_APX_TETSUZANKO: BString = BString::str("BA_MUS_Component_APX_Tetsuzanko");
pub const BA_MUS_COMPONENT_APX_THE_ENTERTAINER: BString = BString::str("BA_MUS_Component_APX_TheEntertainer");
pub const BA_MUS_COMPONENT_APX_TO_THE_END: BString = BString::str("BA_MUS_Component_APX_ToTheEnd");
pub const BA_MUS_COMPONENT_APX_TRANQUIL: BString = BString::str("BA_MUS_Component_APX_Tranquil");
pub const BA_MUS_COMPONENT_APX_WINGS: BString = BString::str("BA_MUS_Component_APX_Wings");
pub const BA_MUS_COMPONENT_APX_WONDER: BString = BString::str("BA_MUS_Component_APX_Wonder");
pub const BA_MUS_COMPONENT_BASIL_BRAIN_CHATTER: BString = BString::str("BA_MUS_Component_Basil_BrainChatter");
pub const BA_MUS_COMPONENT_BASIL_COFFEE_SHOP: BString = BString::str("BA_MUS_Component_Basil_CoffeeShop");
pub const BA_MUS_COMPONENT_BASIL_DRIVE_AT_DUSK: BString = BString::str("BA_MUS_Component_Basil_DriveAtDusk");
pub const BA_MUS_COMPONENT_BASIL_HER_WAY: BString = BString::str("BA_MUS_Component_Basil_HerWay");
pub const BA_MUS_COMPONENT_BASIL_JOURNEY_THROUGH_TIME: BString = BString::str("BA_MUS_Component_Basil_JourneyThroughTime");
pub const BA_MUS_COMPONENT_BASIL_MARCHING_THROUGH_THE_CLOUDS: BString = BString::str("BA_MUS_Component_Basil_MarchingThroughTheClouds");
pub const BA_MUS_COMPONENT_BASIL_MR_ALBERTSON: BString = BString::str("BA_MUS_Component_Basil_MrAlbertson");
pub const BA_MUS_COMPONENT_BASIL_NIGHTS: BString = BString::str("BA_MUS_Component_Basil_Nights");
pub const BA_MUS_COMPONENT_BASIL_OCEAN_SIDE: BString = BString::str("BA_MUS_Component_Basil_OceanSide");
pub const BA_MUS_COMPONENT_BASIL_PUZZLED: BString = BString::str("BA_MUS_Component_Basil_Puzzled");
pub const BA_MUS_COMPONENT_BASIL_QUANTUM: BString = BString::str("BA_MUS_Component_Basil_Quantum");
pub const BA_MUS_COMPONENT_BASIL_SPACED: BString = BString::str("BA_MUS_Component_Basil_Spaced");
pub const BA_MUS_COMPONENT_BASIL_SUNSET_COFFEE: BString = BString::str("BA_MUS_Component_Basil_SunsetCoffee");
pub const BA_MUS_COMPONENT_CUSTARD: BString = BString::str("BA_MUS_Component_Custard");
pub const BA_MUS_COMPONENT_EL_DUO: BString = BString::str("BA_MUS_Component_El_Duo");
pub const BA_MUS_COMPONENT_FOUNTAINTAIL: BString = BString::str("BA_MUS_Component_Fountaintail");
pub const BA_MUS_COMPONENT_JOHNNY_LEDGER_CRYSTAL_TOWER: BString = BString::str("BA_MUS_Component_JohnnyLedger_CrystalTower");
pub const BA_MUS_COMPONENT_JOHNNY_LEDGER_LANDING_PAGE: BString = BString::str("BA_MUS_Component_JohnnyLedger_LandingPage");
pub const BA_MUS_COMPONENT_JOHNNY_LEDGER_UNCOUTH_MEETING: BString = BString::str("BA_MUS_Component_JohnnyLedger_UncouthMeeting");
pub const BA_MUS_COMPONENT_MORNING_DREAM: BString = BString::str("BA_MUS_Component_Morning_Dream");
pub const BA_MUS_COMPONENT_OST_90S: BString = BString::str("BA_MUS_Component_OST_90s");
pub const BA_MUS_COMPONENT_OST_AESTHETICS: BString = BString::str("BA_MUS_Component_OST_Aesthetics");
pub const BA_MUS_COMPONENT_OST_DRIFTING_IN_SPACE: BString = BString::str("BA_MUS_Component_OST_Drifting_in_Space");
pub const BA_MUS_COMPONENT_OST_FAMILIAR: BString = BString::str("BA_MUS_Component_OST_Familiar");
pub const BA_MUS_COMPONENT_OST_FROZEN_MOO: BString = BString::str("BA_MUS_Component_OST_Frozen_Moo");
pub const BA_MUS_COMPONENT_OST_HARD_BASS: BString = BString::str("BA_MUS_Component_OST_Hard_Bass");
pub const BA_MUS_COMPONENT_OST_IMPOSTER: BString = BString::str("BA_MUS_Component_OST_Imposter");
pub const BA_MUS_COMPONENT_OST_PENSIVE: BString = BString::str("BA_MUS_Component_OST_Pensive");
pub const BA_MUS_COMPONENT_OST_SOUNDS_GOOD: BString = BString::str("BA_MUS_Component_OST_SoundsGood");
pub const BA_MUS_COMPONENT_OST_SPUNKY: BString = BString::str("BA_MUS_Component_OST_Spunky");
pub const BA_MUS_COMPONENT_OST_STRATEGIZE: BString = BString::str("BA_MUS_Component_OST_Strategize");
pub const BA_MUS_COMPONENT_OST_VIBE: BString = BString::str("BA_MUS_Component_OST_Vibe");
pub const BA_MUS_COMPONENT_RETRO_BOSS: BString = BString::str("BA_MUS_Component_Retro_Boss");
pub const BA_MUS_COMPONENT_RETRO_MENU: BString = BString::str("BA_MUS_Component_Retro_Menu");
pub const BA_MUS_COMPONENT_RETRO_STAGE_1: BString = BString::str("BA_MUS_Component_Retro_Stage_1");
pub const BA_MUS_COMPONENT_RETRO_STAGE_2: BString = BString::str("BA_MUS_Component_Retro_Stage_2");
pub const BA_MUS_COMPONENT_RETRO_STAGE_3: BString = BString::str("BA_MUS_Component_Retro_Stage_3");
pub const BA_MUS_COMPONENT_RETRO_STAGE_4: BString = BString::str("BA_MUS_Component_Retro_Stage_4");
pub const BA_MUS_COMPONENT_RETRO_STAGE_5: BString = BString::str("BA_MUS_Component_Retro_Stage_5");
pub const BA_MUS_COMPONENT_SOLUTION_NOT_FORTHCOMING: BString = BString::str("BA_MUS_Component_Solution_Not_Forthcoming");
pub const BA_MUS_COMPONENT_THUNDERPUNCH_A: BString = BString::str("BA_MUS_Component_Thunderpunch_A");
pub const BA_MUS_COMPONENT_THUNDERPUNCH_B: BString = BString::str("BA_MUS_Component_Thunderpunch_B");
pub const BA_MUS_COMPONENT_THUNDERPUNCH_DRONE: BString = BString::str("BA_MUS_Component_Thunderpunch_Drone");
pub const BA_MUS_COMPONENT_SPZI_AT_THE_FAIR: BString = BString::str("BA_MUS_Component_spzi_AtTheFair");
pub const BA_MUS_COMPONENT_SPZI_CORAL: BString = BString::str("BA_MUS_Component_spzi_Coral");
pub const BA_MUS_COMPONENT_SPZI_CRYPT: BString = BString::str("BA_MUS_Component_spzi_Crypt");
pub const BA_MUS_COMPONENT_SPZI_DEEP_SEA_CREATURE: BString = BString::str("BA_MUS_Component_spzi_DeepSeaCreature");
pub const BA_MUS_COMPONENT_SPZI_ICY_HALLS: BString = BString::str("BA_MUS_Component_spzi_IcyHalls");
pub const BA_MUS_COMPONENT_SPZI_SECRET_CHAMBER: BString = BString::str("BA_MUS_Component_spzi_SecretChamber");
pub const BA_MUS_COMPONENT_SPZI_SERENE: BString = BString::str("BA_MUS_Component_spzi_Serene");
pub const BA_MUS_COMPONENT_SPZI_THE_ACADEMY: BString = BString::str("BA_MUS_Component_spzi_TheAcademy");
pub const BA_MUS_COMPONENT_SPZI_THE_LAB: BString = BString::str("BA_MUS_Component_spzi_TheLab");
pub const BA_MUS_COMPONENT_SPZI_VINE_ALLEY: BString = BString::str("BA_MUS_Component_spzi_VineAlley");
pub const BA_MUS_COMPONENT_VIWRAP_SHOP: BString = BString::str("BA_MUS_Component_viwrap_Shop");
pub const BA_MUS_COMPONENT_VIWRAP_SWAMP: BString = BString::str("BA_MUS_Component_viwrap_Swamp");
pub const BA_MUS_COMPONENT_VIWRAP_TENSION: BString = BString::str("BA_MUS_Component_viwrap_Tension");
pub const BA_MUS_NEW_BEGINNING_WINTER_HOLIDAY: BString = BString::str("BA_MUS_New_Beginning_Winter_Holiday");
pub const BA_MUS_OST_HOME: BString = BString::str("BA_MUS_OST_Home");
pub const BA_MUS_OST_INCANDESCENT: BString = BString::str("BA_MUS_OST_Incandescent");
pub const BA_MUS_OST_LAST_HURRAH: BString = BString::str("BA_MUS_OST_Last_Hurrah");
pub const BA_MUS_OST_MIST: BString = BString::str("BA_MUS_OST_Mist");
pub const BA_MUS_OST_NEW_BEGINNING: BString = BString::str("BA_MUS_OST_New_Beginning");
pub const BA_MUS_OST_PARALLELS: BString = BString::str("BA_MUS_OST_Parallels");
pub const BA_MUS_OST_PERPETUAL_THOUGHT: BString = BString::str("BA_MUS_OST_Perpetual_Thought");
pub const BA_MUS_OST_PHOSPHORESCENCE: BString = BString::str("BA_MUS_OST_Phosphorescence");
pub const BA_MUS_OST_RADIANCE: BString = BString::str("BA_MUS_OST_Radiance");
pub const BA_MUS_OST_REFLECTIONS: BString = BString::str("BA_MUS_OST_Reflections");
pub const BA_MUS_OST_SALUTATIONS: BString = BString::str("BA_MUS_OST_Salutations");
pub const BA_MUS_OST_SHIMMER: BString = BString::str("BA_MUS_OST_Shimmer");
pub const BA_NEON_LIGHT1: BString = BString::str("BA_NeonLight1");
pub const BA_OLD_COMPUTER: BString = BString::str("BA_Old_Computer");
pub const BA_PRINTER: BString = BString::str("BA_Printer");
pub const BA_PRINTER_2: BString = BString::str("BA_Printer_2");
pub const BA_RADIO_STATIC1: BString = BString::str("BA_RadioStatic1");
pub const BA_SYNTH_BASIC_SAWTOOTH: BString = BString::str("BA_Synth_Basic_Sawtooth");
pub const BA_SYNTH_BASIC_SINE: BString = BString::str("BA_Synth_Basic_Sine");
pub const BA_SYNTH_BASIC_SQUARE: BString = BString::str("BA_Synth_Basic_Square");
pub const BA_SYNTH_BASIC_TRIANGLE: BString = BString::str("BA_Synth_Basic_Triangle");
pub const BA_SYNTH_NOISE_PINK: BString = BString::str("BA_Synth_Noise_Pink");
pub const BA_SYNTH_NOISE_WHITE: BString = BString::str("BA_Synth_Noise_White");
pub const BA_THUMPY_MACHINE: BString = BString::str("BA_Thumpy_Machine");
pub const BA_WATER_FLOWING_CALM: BString = BString::str("BA_Water_Flowing_Calm");
pub const BA_WATER_FLOWING_FOUNTAIN: BString = BString::str("BA_Water_Flowing_Fountain");
pub const BA_WATER_FLOWING_WATERFALL: BString = BString::str("BA_Water_Flowing_Waterfall");
pub const BA_WATER_FLOWING_WAVES: BString = BString::str("BA_Water_Flowing_Waves");
pub const BA_WATER_RESTING_LAKE_SHORE_NOISY: BString = BString::str("BA_Water_Resting_LakeShore_Noisy");
pub const BA_WATER_RESTING_LAKE_SHORE_STILL: BString = BString::str("BA_Water_Resting_LakeShore_Still");
pub const MUS_APX_APOGEE: BString = BString::str("MUS_APX_Apogee");
pub const MUS_APX_CANOPY_OF_LIGHT: BString = BString::str("MUS_APX_Canopy_of_Light");
pub const MUS_APX_MICRO: BString = BString::str("MUS_APX_Micro");

pub const BRICK_AUDIO_DESCRIPTOR_ASSETS: &[BString] = &[
    BA_AMB_ABSTRACT_SUBTLE_INTERFERENCE,
    BA_AMB_COMPONENT_AIR_CONDITIONING_BUZZY_1,
    BA_AMB_COMPONENT_AIR_CONDITIONING_BUZZY_2,
    BA_AMB_COMPONENT_AIR_CONDITIONING_GRUNGY,
    BA_AMB_COMPONENT_AIR_CONDITIONING_WOBBLY,
    BA_AMB_COMPONENT_ALARM_SCIFI_CREEPY,
    BA_AMB_COMPONENT_ALARM_SCIFI_WARNING_1,
    BA_AMB_COMPONENT_ALARM_SCIFI_WARNING_2,
    BA_AMB_COMPONENT_ALARM_SCIFI_WARNING_3,
    BA_AMB_COMPONENT_AUTOMATED_VENDING,
    BA_AMB_COMPONENT_FIRES_FIREPLACE_1,
    BA_AMB_COMPONENT_HORN_CAR_GENERIC,
    BA_AMB_COMPONENT_HORN_CAR_SMALL,
    BA_AMB_COMPONENT_HORN_CAR_TRUCK,
    BA_AMB_COMPONENT_HOSPITAL_MISC_RESPIRATOR,
    BA_AMB_COMPONENT_HOSPITAL_MONITORS_HEART_1,
    BA_AMB_COMPONENT_HOSPITAL_MONITORS_HEART_2,
    BA_AMB_COMPONENT_HOSPITAL_MONITORS_HEART_3,
    BA_AMB_EXTERIOR_CITY,
    BA_AMB_EXTERIOR_CONSTRUCTION_HEAVY,
    BA_AMB_EXTERIOR_CONSTRUCTION_LIGHT,
    BA_AMB_EXTERIOR_COURTYARD,
    BA_AMB_EXTERIOR_GENTLE_FOREST,
    BA_AMB_EXTERIOR_NIGHT_CRICKETS,
    BA_AMB_EXTERIOR_NOISY_FOREST,
    BA_AMB_EXTERIOR_WINDY_FOREST,
    BA_AMB_EXTERIOR_WINDY_MOUNTAIN,
    BA_AMB_INTERIOR_AIRCRAFT_CABIN_GENTLE,
    BA_AMB_INTERIOR_AIRCRAFT_CABIN_INTENSE,
    BA_AMB_INTERIOR_DRIPPY_TUNNEL,
    BA_AMB_INTERIOR_ELECTRIC,
    BA_AMB_INTERIOR_ELEVATOR_SHAFT,
    BA_AMB_INTERIOR_LOW_FREQUENCY,
    BA_AMB_INTERIOR_QUIET_AIRCONDITIONING,
    BA_AMB_INTERIOR_SERVER_ROOM,
    BA_AMB_INTERIOR_SPACE_TUNNEL,
    BA_AMB_INTERIOR_UNDERWATER,
    BA_AIR_RAID_SIREN1,
    BA_ALARMS_HOUSEHOLD_ALARM_CLOCK,
    BA_ALARMS_HOUSEHOLD_BELLS,
    BA_ALARMS_HOUSEHOLD_BURGLAR,
    BA_ALARMS_HOUSEHOLD_CAR,
    BA_ALARMS_HOUSEHOLD_SMOKE,
    BA_ALARMS_HOUSEHOLD_WATCH_FAST,
    BA_ALARMS_HOUSEHOLD_WATCH_SLOW,
    BA_ALARMS_INDUSTRIAL_BELL,
    BA_ALARMS_INDUSTRIAL_SECURITY,
    BA_ALARMS_INDUSTRIAL_TRUCK,
    BA_CREAKING_METAL_SQUEAKY,
    BA_CREAKING_METAL_STRAINING,
    BA_CREAKING_METAL_STRESS,
    BA_CREAKING_WOOD_CONSTANT_RATTLING,
    BA_CREAKING_WOOD_INTERIOR,
    BA_CREAKING_WOOD_MASSIVE,
    BA_CREAKING_WOOD_WAVING,
    BA_DEEP_MACHINE,
    BA_ELECTRIC_MOTOR_1,
    BA_FAUNA_BIRDS_ALDER_FLYCATCHER,
    BA_FAUNA_BIRDS_MIXED,
    BA_FAUNA_BIRDS_NIGHTINGALE,
    BA_JACOBS_LADDER,
    BA_JACUZZI,
    BA_KITCHEN_DISHES,
    BA_KITCHEN_DISHWASHER_COLLECTING_WATER,
    BA_KITCHEN_DISHWASHER_RUNNING,
    BA_KITCHEN_FRYING_FOOD_LARGE,
    BA_KITCHEN_FRYING_FOOD_SMALL,
    BA_MUS_COMPONENT_APX_ALLEGRO,
    BA_MUS_COMPONENT_APX_APOGEE,
    BA_MUS_COMPONENT_APX_ARCADIA,
    BA_MUS_COMPONENT_APX_ARENA,
    BA_MUS_COMPONENT_APX_CANOPY_OF_LIGHT,
    BA_MUS_COMPONENT_APX_CARRIER,
    BA_MUS_COMPONENT_APX_CLOCKWORK,
    BA_MUS_COMPONENT_APX_CRYPT,
    BA_MUS_COMPONENT_APX_ELEGANT,
    BA_MUS_COMPONENT_APX_ENCHANTMENT,
    BA_MUS_COMPONENT_APX_EXPLORERS,
    BA_MUS_COMPONENT_APX_FROG,
    BA_MUS_COMPONENT_APX_FUSION,
    BA_MUS_COMPONENT_APX_LA_ROSA,
    BA_MUS_COMPONENT_APX_LUX,
    BA_MUS_COMPONENT_APX_MAINFRAME,
    BA_MUS_COMPONENT_APX_MAJESTIC,
    BA_MUS_COMPONENT_APX_MELLOW,
    BA_MUS_COMPONENT_APX_MICRO,
    BA_MUS_COMPONENT_APX_MISSION,
    BA_MUS_COMPONENT_APX_MOMENT,
    BA_MUS_COMPONENT_APX_MOOD,
    BA_MUS_COMPONENT_APX_MUSICBOX,
    BA_MUS_COMPONENT_APX_NOIR,
    BA_MUS_COMPONENT_APX_OASIS,
    BA_MUS_COMPONENT_APX_OPEN_RANGE,
    BA_MUS_COMPONENT_APX_PULSE,
    BA_MUS_COMPONENT_APX_REFRACTION,
    BA_MUS_COMPONENT_APX_SANCTUARY,
    BA_MUS_COMPONENT_APX_SERENITY,
    BA_MUS_COMPONENT_APX_SET_SAIL,
    BA_MUS_COMPONENT_APX_SHADOW,
    BA_MUS_COMPONENT_APX_SPIES,
    BA_MUS_COMPONENT_APX_STANCED,
    BA_MUS_COMPONENT_APX_STROLL,
    BA_MUS_COMPONENT_APX_TESTAROSSA,
    BA_MUS_COMPONENT_APX_TETSUZANKO,
    BA_MUS_COMPONENT_APX_THE_ENTERTAINER,
    BA_MUS_COMPONENT_APX_TO_THE_END,
    BA_MUS_COMPONENT_APX_TRANQUIL,
    BA_MUS_COMPONENT_APX_WINGS,
    BA_MUS_COMPONENT_APX_WONDER,
    BA_MUS_COMPONENT_BASIL_BRAIN_CHATTER,
    BA_MUS_COMPONENT_BASIL_COFFEE_SHOP,
    BA_MUS_COMPONENT_BASIL_DRIVE_AT_DUSK,
    BA_MUS_COMPONENT_BASIL_HER_WAY,
    BA_MUS_COMPONENT_BASIL_JOURNEY_THROUGH_TIME,
    BA_MUS_COMPONENT_BASIL_MARCHING_THROUGH_THE_CLOUDS,
    BA_MUS_COMPONENT_BASIL_MR_ALBERTSON,
    BA_MUS_COMPONENT_BASIL_NIGHTS,
    BA_MUS_COMPONENT_BASIL_OCEAN_SIDE,
    BA_MUS_COMPONENT_BASIL_PUZZLED,
    BA_MUS_COMPONENT_BASIL_QUANTUM,
    BA_MUS_COMPONENT_BASIL_SPACED,
    BA_MUS_COMPONENT_BASIL_SUNSET_COFFEE,
    BA_MUS_COMPONENT_CUSTARD,
    BA_MUS_COMPONENT_EL_DUO,
    BA_MUS_COMPONENT_FOUNTAINTAIL,
    BA_MUS_COMPONENT_JOHNNY_LEDGER_CRYSTAL_TOWER,
    BA_MUS_COMPONENT_JOHNNY_LEDGER_LANDING_PAGE,
    BA_MUS_COMPONENT_JOHNNY_LEDGER_UNCOUTH_MEETING,
    BA_MUS_COMPONENT_MORNING_DREAM,
    BA_MUS_COMPONENT_OST_90S,
    BA_MUS_COMPONENT_OST_AESTHETICS,
    BA_MUS_COMPONENT_OST_DRIFTING_IN_SPACE,
    BA_MUS_COMPONENT_OST_FAMILIAR,
    BA_MUS_COMPONENT_OST_FROZEN_MOO,
    BA_MUS_COMPONENT_OST_HARD_BASS,
    BA_MUS_COMPONENT_OST_IMPOSTER,
    BA_MUS_COMPONENT_OST_PENSIVE,
    BA_MUS_COMPONENT_OST_SOUNDS_GOOD,
    BA_MUS_COMPONENT_OST_SPUNKY,
    BA_MUS_COMPONENT_OST_STRATEGIZE,
    BA_MUS_COMPONENT_OST_VIBE,
    BA_MUS_COMPONENT_RETRO_BOSS,
    BA_MUS_COMPONENT_RETRO_MENU,
    BA_MUS_COMPONENT_RETRO_STAGE_1,
    BA_MUS_COMPONENT_RETRO_STAGE_2,
    BA_MUS_COMPONENT_RETRO_STAGE_3,
    BA_MUS_COMPONENT_RETRO_STAGE_4,
    BA_MUS_COMPONENT_RETRO_STAGE_5,
    BA_MUS_COMPONENT_SOLUTION_NOT_FORTHCOMING,
    BA_MUS_COMPONENT_THUNDERPUNCH_A,
    BA_MUS_COMPONENT_THUNDERPUNCH_B,
    BA_MUS_COMPONENT_THUNDERPUNCH_DRONE,
    BA_MUS_COMPONENT_SPZI_AT_THE_FAIR,
    BA_MUS_COMPONENT_SPZI_CORAL,
    BA_MUS_COMPONENT_SPZI_CRYPT,
    BA_MUS_COMPONENT_SPZI_DEEP_SEA_CREATURE,
    BA_MUS_COMPONENT_SPZI_ICY_HALLS,
    BA_MUS_COMPONENT_SPZI_SECRET_CHAMBER,
    BA_MUS_COMPONENT_SPZI_SERENE,
    BA_MUS_COMPONENT_SPZI_THE_ACADEMY,
    BA_MUS_COMPONENT_SPZI_THE_LAB,
    BA_MUS_COMPONENT_SPZI_VINE_ALLEY,
    BA_MUS_COMPONENT_VIWRAP_SHOP,
    BA_MUS_COMPONENT_VIWRAP_SWAMP,
    BA_MUS_COMPONENT_VIWRAP_TENSION,
    BA_MUS_NEW_BEGINNING_WINTER_HOLIDAY,
    BA_MUS_OST_HOME,
    BA_MUS_OST_INCANDESCENT,
    BA_MUS_OST_LAST_HURRAH,
    BA_MUS_OST_MIST,
    BA_MUS_OST_NEW_BEGINNING,
    BA_MUS_OST_PARALLELS,
    BA_MUS_OST_PERPETUAL_THOUGHT,
    BA_MUS_OST_PHOSPHORESCENCE,
    BA_MUS_OST_RADIANCE,
    BA_MUS_OST_REFLECTIONS,
    BA_MUS_OST_SALUTATIONS,
    BA_MUS_OST_SHIMMER,
    BA_NEON_LIGHT1,
    BA_OLD_COMPUTER,
    BA_PRINTER,
    BA_PRINTER_2,
    BA_RADIO_STATIC1,
    BA_SYNTH_BASIC_SAWTOOTH,
    BA_SYNTH_BASIC_SINE,
    BA_SYNTH_BASIC_SQUARE,
    BA_SYNTH_BASIC_TRIANGLE,
    BA_SYNTH_NOISE_PINK,
    BA_SYNTH_NOISE_WHITE,
    BA_THUMPY_MACHINE,
    BA_WATER_FLOWING_CALM,
    BA_WATER_FLOWING_FOUNTAIN,
    BA_WATER_FLOWING_WATERFALL,
    BA_WATER_FLOWING_WAVES,
    BA_WATER_RESTING_LAKE_SHORE_NOISY,
    BA_WATER_RESTING_LAKE_SHORE_STILL,
    MUS_APX_APOGEE,
    MUS_APX_CANOPY_OF_LIGHT,
    MUS_APX_MICRO,
];

// === BrickFontDescriptor (25) ===
pub const AAAIIGHT: BString = BString::str("Aaaiight");
pub const BAD_COMIC: BString = BString::str("BadComic");
pub const BLACK_OPS_ONE: BString = BString::str("BlackOpsOne");
pub const BUNGEE: BString = BString::str("Bungee");
pub const CHERRY_BOMB_ONE: BString = BString::str("CherryBombOne");
pub const CINZEL: BString = BString::str("Cinzel");
pub const EAGLE_LAKE: BString = BString::str("EagleLake");
pub const GLACIAL_INDIFFERENCE: BString = BString::str("GlacialIndifference");
pub const GLACIAL_INDIFFERENCE_PLUS: BString = BString::str("GlacialIndifferencePlus");
pub const GOTFRIDUS: BString = BString::str("Gotfridus");
pub const IOSEVKA_TERM: BString = BString::str("IosevkaTerm");
pub const IOSEVKA_TERM_SLAB: BString = BString::str("IosevkaTermSlab");
pub const KURLAND: BString = BString::str("Kurland");
pub const MONASPACE_ARGON: BString = BString::str("MonaspaceArgon");
pub const MONASPACE_KRYPTON: BString = BString::str("MonaspaceKrypton");
pub const MONASPACE_NEON: BString = BString::str("MonaspaceNeon");
pub const MONASPACE_RADON: BString = BString::str("MonaspaceRadon");
pub const MONASPACE_XENON: BString = BString::str("MonaspaceXenon");
pub const MOST_WASTED: BString = BString::str("MostWasted");
pub const NOTO_SANS: BString = BString::str("NotoSans");
pub const NOTO_SERIF: BString = BString::str("NotoSerif");
pub const ORBITRON: BString = BString::str("Orbitron");
pub const PIRATA_ONE: BString = BString::str("PirataOne");
pub const ROBOTO: BString = BString::str("Roboto");
pub const ROBOTO_MONO: BString = BString::str("RobotoMono");

pub const BRICK_FONT_DESCRIPTOR_ASSETS: &[BString] = &[
    AAAIIGHT,
    BAD_COMIC,
    BLACK_OPS_ONE,
    BUNGEE,
    CHERRY_BOMB_ONE,
    CINZEL,
    EAGLE_LAKE,
    GLACIAL_INDIFFERENCE,
    GLACIAL_INDIFFERENCE_PLUS,
    GOTFRIDUS,
    IOSEVKA_TERM,
    IOSEVKA_TERM_SLAB,
    KURLAND,
    MONASPACE_ARGON,
    MONASPACE_KRYPTON,
    MONASPACE_NEON,
    MONASPACE_RADON,
    MONASPACE_XENON,
    MOST_WASTED,
    NOTO_SANS,
    NOTO_SERIF,
    ORBITRON,
    PIRATA_ONE,
    ROBOTO,
    ROBOTO_MONO,
];

// === BrickOneShotAudioDescriptor (126) ===
pub const BOSA_AMR_FIRE: BString = BString::str("BOSA_AMR_Fire");
pub const BOSA_AP_CARBINE_FIRE: BString = BString::str("BOSA_APCarbine_Fire");
pub const BOSA_AUTO_SHOTGUN_FIRE: BString = BString::str("BOSA_AutoShotgun_Fire");
pub const BOSA_AUTO_SHOTGUN_LAST_FIRE: BString = BString::str("BOSA_AutoShotgun_Last_Fire");
pub const BOSA_BARRAGE_LAUNCHER_FIRE: BString = BString::str("BOSA_BarrageLauncher_Fire");
pub const BOSA_BOLT_ACTION_RIFLE_FIRE: BString = BString::str("BOSA_BoltActionRifle_Fire");
pub const BOSA_BOW_FIRE: BString = BString::str("BOSA_Bow_Fire");
pub const BOSA_BOX_PISTOL_FIRE: BString = BString::str("BOSA_BoxPistol_Fire");
pub const BOSA_BULLPUP_RIFLE_FIRE: BString = BString::str("BOSA_BullpupRifle_Fire");
pub const BOSA_BULLPUP_SMG_FIRE: BString = BString::str("BOSA_BullpupSMG_Fire");
pub const BOSA_BUTTONS_BUTTON_1_PRESS: BString = BString::str("BOSA_Buttons_Button_1_Press");
pub const BOSA_BUTTONS_BUTTON_1_RELEASE: BString = BString::str("BOSA_Buttons_Button_1_Release");
pub const BOSA_BUTTONS_BUTTON_2_PRESS: BString = BString::str("BOSA_Buttons_Button_2_Press");
pub const BOSA_BUTTONS_BUTTON_2_RELEASE: BString = BString::str("BOSA_Buttons_Button_2_Release");
pub const BOSA_BUTTONS_BUTTON_3_PRESS: BString = BString::str("BOSA_Buttons_Button_3_Press");
pub const BOSA_BUTTONS_BUTTON_3_RELEASE: BString = BString::str("BOSA_Buttons_Button_3_Release");
pub const BOSA_DERRINGER_FIRE: BString = BString::str("BOSA_Derringer_Fire");
pub const BOSA_FLINTLOCK_FIRE: BString = BString::str("BOSA_Flintlock_Fire");
pub const BOSA_GUARD_PISTOL_FIRE: BString = BString::str("BOSA_GuardPistol_Fire");
pub const BOSA_GUARD_PISTOL_SUPPRESSED_FIRE: BString = BString::str("BOSA_GuardPistol_Suppressed_Fire");
pub const BOSA_HEAVY_ASSAULT_RIFLE_FIRE: BString = BString::str("BOSA_HeavyAssaultRifle_Fire");
pub const BOSA_HEAVY_SMG_FIRE: BString = BString::str("BOSA_HeavySMG_Fire");
pub const BOSA_HIGH_POWER_PISTOL_FIRE: BString = BString::str("BOSA_HighPowerPistol_Fire");
pub const BOSA_HUNTING_SHOTGUN_FIRE: BString = BString::str("BOSA_HuntingShotgun_Fire");
pub const BOSA_HUNTING_SHOTGUN_LAST_FIRE: BString = BString::str("BOSA_HuntingShotgun_Last_Fire");
pub const BOSA_LEVER_ACTION_FIRE: BString = BString::str("BOSA_LeverAction_Fire");
pub const BOSA_LIGHT_MACHINE_GUN_FIRE: BString = BString::str("BOSA_LightMachineGun_Fire");
pub const BOSA_MAGNUM_FIRE: BString = BString::str("BOSA_Magnum_Fire");
pub const BOSA_MICRO_SMG_FIRE: BString = BString::str("BOSA_MicroSMG_Fire");
pub const BOSA_MINIGUN_FIRE: BString = BString::str("BOSA_Minigun_Fire");
pub const BOSA_PDW_FIRE: BString = BString::str("BOSA_PDW_Fire");
pub const BOSA_PISTOL_FIRE: BString = BString::str("BOSA_Pistol_Fire");
pub const BOSA_PULSE_CARBINE_FIRE: BString = BString::str("BOSA_PulseCarbine_Fire");
pub const BOSA_RAILGUN_FIRE: BString = BString::str("BOSA_Railgun_Fire");
pub const BOSA_REVOLVER_FIRE: BString = BString::str("BOSA_Revolver_Fire");
pub const BOSA_SEMI_AUTO_RIFLE_FIRE: BString = BString::str("BOSA_SemiAutoRifle_Fire");
pub const BOSA_SERVICE_RIFLE_FIRE: BString = BString::str("BOSA_ServiceRifle_Fire");
pub const BOSA_SLUG_SHOTGUN_FIRE: BString = BString::str("BOSA_SlugShotgun_Fire");
pub const BOSA_SLUG_SHOTGUN_LAST_FIRE: BString = BString::str("BOSA_SlugShotgun_Last_Fire");
pub const BOSA_STAMPED_SMG_FIRE: BString = BString::str("BOSA_StampedSMG_Fire");
pub const BOSA_SUPER_SHOTGUN_FIRE: BString = BString::str("BOSA_SuperShotgun_Fire");
pub const BOSA_SUPPRESSED_ASSAULT_RIFLE_FIRE: BString = BString::str("BOSA_SuppressedAssaultRifle_Fire");
pub const BOSA_TACTICAL_SMG_FIRE: BString = BString::str("BOSA_TacticalSMG_Fire");
pub const BOSA_TACTICAL_SHOTGUN_FIRE: BString = BString::str("BOSA_TacticalShotgun_Fire");
pub const BOSA_TACTICAL_SHOTGUN_LAST_FIRE: BString = BString::str("BOSA_TacticalShotgun_Last_Fire");
pub const BOSA_TYPEWRITER_FIRE: BString = BString::str("BOSA_Typewriter_Fire");
pub const BOSA_UNSUPPRESSED_SMG_FIRE: BString = BString::str("BOSA_UnsuppressedSMG_Fire");
pub const OBA_AIR_BRAKE: BString = BString::str("OBA_Air_Brake");
pub const OBA_BR_CHECKPOINT_ACQUIRE_CLICK_CUE: BString = BString::str("OBA_BR_Checkpoint_Acquire_Click_Cue");
pub const OBA_BEEP_1: BString = BString::str("OBA_Beep_1");
pub const OBA_BEEP_2: BString = BString::str("OBA_Beep_2");
pub const OBA_BEEP_3: BString = BString::str("OBA_Beep_3");
pub const OBA_BEEP_4: BString = BString::str("OBA_Beep_4");
pub const OBA_BEEP_5: BString = BString::str("OBA_Beep_5");
pub const OBA_BEEP_6: BString = BString::str("OBA_Beep_6");
pub const OBA_BRICKTIONARY_GUESS: BString = BString::str("OBA_Bricktionary_Guess");
pub const OBA_BRICKTIONARY_MATCH_COMPLETE: BString = BString::str("OBA_Bricktionary_Match_Complete");
pub const OBA_BRICKTIONARY_ROUND_LOST: BString = BString::str("OBA_Bricktionary_Round_Lost");
pub const OBA_BRICKTIONARY_ROUND_START: BString = BString::str("OBA_Bricktionary_Round_Start");
pub const OBA_BRICKTIONARY_ROUND_WIN: BString = BString::str("OBA_Bricktionary_Round_Win");
pub const OBA_CAMERA_FLASH_1: BString = BString::str("OBA_Camera_Flash_1");
pub const OBA_CAMERA_FLASH_2: BString = BString::str("OBA_Camera_Flash_2");
pub const OBA_CAMERA_FLASH_3: BString = BString::str("OBA_Camera_Flash_3");
pub const OBA_CASH_REGISTER_DING: BString = BString::str("OBA_CashRegister_Ding");
pub const OBA_CASH_REGISTER_DING_2: BString = BString::str("OBA_CashRegister_Ding_2");
pub const OBA_CASH_REGISTER_KEYPAD: BString = BString::str("OBA_CashRegister_Keypad");
pub const OBA_DEATHMATCH_ROUND_END: BString = BString::str("OBA_Deathmatch_Round_End");
pub const OBA_DEATHMATCH_ROUND_START: BString = BString::str("OBA_Deathmatch_Round_Start");
pub const OBA_DOOR_BELL_1: BString = BString::str("OBA_DoorBell_1");
pub const OBA_DOOR_BELL_2: BString = BString::str("OBA_DoorBell_2");
pub const OBA_DOOR_BELL_3: BString = BString::str("OBA_DoorBell_3");
pub const OBA_DOOR_BELL_SCI_FI: BString = BString::str("OBA_DoorBell_SciFi");
pub const OBA_DOOR_KNOCK_HARD: BString = BString::str("OBA_Door_Knock_Hard");
pub const OBA_DOOR_KNOCK_SOFT: BString = BString::str("OBA_Door_Knock_Soft");
pub const OBA_DOOR_WOOD2_CLOSE: BString = BString::str("OBA_Door_Wood2_Close");
pub const OBA_DOOR_WOOD2_OPEN: BString = BString::str("OBA_Door_Wood2_Open");
pub const OBA_DOOR_WOOD3_CLOSE: BString = BString::str("OBA_Door_Wood3_Close");
pub const OBA_DOOR_WOOD3_OPEN: BString = BString::str("OBA_Door_Wood3_Open");
pub const OBA_DOOR_WOOD_GATE_CLOSE: BString = BString::str("OBA_Door_WoodGate_Close");
pub const OBA_DOOR_WOOD_GATE_OPEN: BString = BString::str("OBA_Door_WoodGate_Open");
pub const OBA_DOOR_WOOD_CLOSE: BString = BString::str("OBA_Door_Wood_Close");
pub const OBA_DOOR_WOOD_OPEN: BString = BString::str("OBA_Door_Wood_Open");
pub const OBA_GLAS_SHATTER_1: BString = BString::str("OBA_GlasShatter_1");
pub const OBA_GLAS_SHATTER_2: BString = BString::str("OBA_GlasShatter_2");
pub const OBA_GLAS_SHATTER_3: BString = BString::str("OBA_GlasShatter_3");
pub const OBA_GLAS_SHATTER_4: BString = BString::str("OBA_GlasShatter_4");
pub const OBA_HAND_BRAKE: BString = BString::str("OBA_HandBrake");
pub const OBA_KEYBOARD: BString = BString::str("OBA_Keyboard");
pub const OBA_KEYPAD: BString = BString::str("OBA_Keypad");
pub const OBA_LEVER1_1: BString = BString::str("OBA_Lever1_1");
pub const OBA_LEVER1_2: BString = BString::str("OBA_Lever1_2");
pub const OBA_LEVER1_3: BString = BString::str("OBA_Lever1_3");
pub const OBA_LEVER1_4: BString = BString::str("OBA_Lever1_4");
pub const OBA_LEVER2_1: BString = BString::str("OBA_Lever2_1");
pub const OBA_LEVER2_2: BString = BString::str("OBA_Lever2_2");
pub const OBA_LEVER2_3: BString = BString::str("OBA_Lever2_3");
pub const OBA_LEVER2_4: BString = BString::str("OBA_Lever2_4");
pub const OBA_LIGHTSWITCH: BString = BString::str("OBA_Lightswitch");
pub const OBA_METAL_STRES1: BString = BString::str("OBA_MetalStres1");
pub const OBA_METAL_STRES2: BString = BString::str("OBA_MetalStres2");
pub const OBA_METAL_STRES3: BString = BString::str("OBA_MetalStres3");
pub const OBA_METAL_STRES4: BString = BString::str("OBA_MetalStres4");
pub const OBA_METAL_STRES_DISTANT_1: BString = BString::str("OBA_MetalStresDistant_1");
pub const OBA_METAL_STRES_DISTANT_2: BString = BString::str("OBA_MetalStresDistant_2");
pub const OBA_NIGHT_VISION: BString = BString::str("OBA_NightVision");
pub const OBA_TOOL_AIR_DRILL: BString = BString::str("OBA_ToolAir_Drill");
pub const OBA_TOOL_PNUEMATIC_DRILL: BString = BString::str("OBA_ToolPnuematic_Drill");
pub const OBA_UI_CHECKPOINT_ACQUIRE_TUNE_CUE: BString = BString::str("OBA_UI_Checkpoint_Acquire_Tune_Cue");
pub const OBA_UI_GOAL_TUNE_CUE: BString = BString::str("OBA_UI_Goal_Tune_Cue");
pub const OBA_VENDING_MACHINE_DISPENSE: BString = BString::str("OBA_Vending_Machine_Dispense");
pub const OBA_VENDING_MACHINE_ENTER_COIN_1: BString = BString::str("OBA_Vending_Machine_Enter_Coin_1");
pub const OBA_VENDING_MACHINE_ENTER_COIN_2: BString = BString::str("OBA_Vending_Machine_Enter_Coin_2");
pub const OBA_WATER_DROPLET_1: BString = BString::str("OBA_Water_Droplet_1");
pub const OBA_WATER_DROPLET_2: BString = BString::str("OBA_Water_Droplet_2");
pub const OBA_WATER_DROPLET_3: BString = BString::str("OBA_Water_Droplet_3");
pub const OBA_WATER_DROPLET_4: BString = BString::str("OBA_Water_Droplet_4");
pub const OBA_WATER_DROPLET_RANDOMIZED: BString = BString::str("OBA_Water_Droplet_Randomized");
pub const OBA_WATER_SPLASH_DROP: BString = BString::str("OBA_Water_Splash_Drop");
pub const OBA_WATER_SPLASH_MASSIVE: BString = BString::str("OBA_Water_Splash_Massive");
pub const OBA_WATER_SPLASH_MEDIUM: BString = BString::str("OBA_Water_Splash_Medium");
pub const OBA_WATER_SPLASH_SMALL: BString = BString::str("OBA_Water_Splash_Small");
pub const OBA_WOOD_CREAK1_1: BString = BString::str("OBA_WoodCreak1_1");
pub const OBA_WOOD_CREAK1_2: BString = BString::str("OBA_WoodCreak1_2");
pub const OBA_WOOD_CREAK1_3: BString = BString::str("OBA_WoodCreak1_3");
pub const OBA_WOOD_CREAK1_4: BString = BString::str("OBA_WoodCreak1_4");
pub const OBA_TIM_SWEENEY: BString = BString::str("OBA_tim_sweeney");

pub const BRICK_ONE_SHOT_AUDIO_DESCRIPTOR_ASSETS: &[BString] = &[
    BOSA_AMR_FIRE,
    BOSA_AP_CARBINE_FIRE,
    BOSA_AUTO_SHOTGUN_FIRE,
    BOSA_AUTO_SHOTGUN_LAST_FIRE,
    BOSA_BARRAGE_LAUNCHER_FIRE,
    BOSA_BOLT_ACTION_RIFLE_FIRE,
    BOSA_BOW_FIRE,
    BOSA_BOX_PISTOL_FIRE,
    BOSA_BULLPUP_RIFLE_FIRE,
    BOSA_BULLPUP_SMG_FIRE,
    BOSA_BUTTONS_BUTTON_1_PRESS,
    BOSA_BUTTONS_BUTTON_1_RELEASE,
    BOSA_BUTTONS_BUTTON_2_PRESS,
    BOSA_BUTTONS_BUTTON_2_RELEASE,
    BOSA_BUTTONS_BUTTON_3_PRESS,
    BOSA_BUTTONS_BUTTON_3_RELEASE,
    BOSA_DERRINGER_FIRE,
    BOSA_FLINTLOCK_FIRE,
    BOSA_GUARD_PISTOL_FIRE,
    BOSA_GUARD_PISTOL_SUPPRESSED_FIRE,
    BOSA_HEAVY_ASSAULT_RIFLE_FIRE,
    BOSA_HEAVY_SMG_FIRE,
    BOSA_HIGH_POWER_PISTOL_FIRE,
    BOSA_HUNTING_SHOTGUN_FIRE,
    BOSA_HUNTING_SHOTGUN_LAST_FIRE,
    BOSA_LEVER_ACTION_FIRE,
    BOSA_LIGHT_MACHINE_GUN_FIRE,
    BOSA_MAGNUM_FIRE,
    BOSA_MICRO_SMG_FIRE,
    BOSA_MINIGUN_FIRE,
    BOSA_PDW_FIRE,
    BOSA_PISTOL_FIRE,
    BOSA_PULSE_CARBINE_FIRE,
    BOSA_RAILGUN_FIRE,
    BOSA_REVOLVER_FIRE,
    BOSA_SEMI_AUTO_RIFLE_FIRE,
    BOSA_SERVICE_RIFLE_FIRE,
    BOSA_SLUG_SHOTGUN_FIRE,
    BOSA_SLUG_SHOTGUN_LAST_FIRE,
    BOSA_STAMPED_SMG_FIRE,
    BOSA_SUPER_SHOTGUN_FIRE,
    BOSA_SUPPRESSED_ASSAULT_RIFLE_FIRE,
    BOSA_TACTICAL_SMG_FIRE,
    BOSA_TACTICAL_SHOTGUN_FIRE,
    BOSA_TACTICAL_SHOTGUN_LAST_FIRE,
    BOSA_TYPEWRITER_FIRE,
    BOSA_UNSUPPRESSED_SMG_FIRE,
    OBA_AIR_BRAKE,
    OBA_BR_CHECKPOINT_ACQUIRE_CLICK_CUE,
    OBA_BEEP_1,
    OBA_BEEP_2,
    OBA_BEEP_3,
    OBA_BEEP_4,
    OBA_BEEP_5,
    OBA_BEEP_6,
    OBA_BRICKTIONARY_GUESS,
    OBA_BRICKTIONARY_MATCH_COMPLETE,
    OBA_BRICKTIONARY_ROUND_LOST,
    OBA_BRICKTIONARY_ROUND_START,
    OBA_BRICKTIONARY_ROUND_WIN,
    OBA_CAMERA_FLASH_1,
    OBA_CAMERA_FLASH_2,
    OBA_CAMERA_FLASH_3,
    OBA_CASH_REGISTER_DING,
    OBA_CASH_REGISTER_DING_2,
    OBA_CASH_REGISTER_KEYPAD,
    OBA_DEATHMATCH_ROUND_END,
    OBA_DEATHMATCH_ROUND_START,
    OBA_DOOR_BELL_1,
    OBA_DOOR_BELL_2,
    OBA_DOOR_BELL_3,
    OBA_DOOR_BELL_SCI_FI,
    OBA_DOOR_KNOCK_HARD,
    OBA_DOOR_KNOCK_SOFT,
    OBA_DOOR_WOOD2_CLOSE,
    OBA_DOOR_WOOD2_OPEN,
    OBA_DOOR_WOOD3_CLOSE,
    OBA_DOOR_WOOD3_OPEN,
    OBA_DOOR_WOOD_GATE_CLOSE,
    OBA_DOOR_WOOD_GATE_OPEN,
    OBA_DOOR_WOOD_CLOSE,
    OBA_DOOR_WOOD_OPEN,
    OBA_GLAS_SHATTER_1,
    OBA_GLAS_SHATTER_2,
    OBA_GLAS_SHATTER_3,
    OBA_GLAS_SHATTER_4,
    OBA_HAND_BRAKE,
    OBA_KEYBOARD,
    OBA_KEYPAD,
    OBA_LEVER1_1,
    OBA_LEVER1_2,
    OBA_LEVER1_3,
    OBA_LEVER1_4,
    OBA_LEVER2_1,
    OBA_LEVER2_2,
    OBA_LEVER2_3,
    OBA_LEVER2_4,
    OBA_LIGHTSWITCH,
    OBA_METAL_STRES1,
    OBA_METAL_STRES2,
    OBA_METAL_STRES3,
    OBA_METAL_STRES4,
    OBA_METAL_STRES_DISTANT_1,
    OBA_METAL_STRES_DISTANT_2,
    OBA_NIGHT_VISION,
    OBA_TOOL_AIR_DRILL,
    OBA_TOOL_PNUEMATIC_DRILL,
    OBA_UI_CHECKPOINT_ACQUIRE_TUNE_CUE,
    OBA_UI_GOAL_TUNE_CUE,
    OBA_VENDING_MACHINE_DISPENSE,
    OBA_VENDING_MACHINE_ENTER_COIN_1,
    OBA_VENDING_MACHINE_ENTER_COIN_2,
    OBA_WATER_DROPLET_1,
    OBA_WATER_DROPLET_2,
    OBA_WATER_DROPLET_3,
    OBA_WATER_DROPLET_4,
    OBA_WATER_DROPLET_RANDOMIZED,
    OBA_WATER_SPLASH_DROP,
    OBA_WATER_SPLASH_MASSIVE,
    OBA_WATER_SPLASH_MEDIUM,
    OBA_WATER_SPLASH_SMALL,
    OBA_WOOD_CREAK1_1,
    OBA_WOOD_CREAK1_2,
    OBA_WOOD_CREAK1_3,
    OBA_WOOD_CREAK1_4,
    OBA_TIM_SWEENEY,
];

// === BrickWheelEngineAudioDescriptor (4) ===
pub const WHEEL_ENGINE_AUDIO_FAMILY01: BString = BString::str("WheelEngineAudio_Family01");
pub const WHEEL_ENGINE_AUDIO_MUSCLE_01: BString = BString::str("WheelEngineAudio_Muscle_01");
pub const WHEEL_ENGINE_AUDIO_RALLY_CAR01: BString = BString::str("WheelEngineAudio_RallyCar01");
pub const WHEEL_ENGINE_AUDIO_SEMI_01: BString = BString::str("WheelEngineAudio_Semi_01");

pub const BRICK_WHEEL_ENGINE_AUDIO_DESCRIPTOR_ASSETS: &[BString] = &[
    WHEEL_ENGINE_AUDIO_FAMILY01,
    WHEEL_ENGINE_AUDIO_MUSCLE_01,
    WHEEL_ENGINE_AUDIO_RALLY_CAR01,
    WHEEL_ENGINE_AUDIO_SEMI_01,
];

/// Every external asset type paired with the slice of its assets.
pub const ASSET_TYPES: &[(&str, &[BString])] = &[
    ("BRItemBase", BR_ITEM_BASE_ASSETS),
    ("BRPickupBase", BR_PICKUP_BASE_ASSETS),
    ("BRWeaponProjectile", BR_WEAPON_PROJECTILE_ASSETS),
    ("BrickAudioDescriptor", BRICK_AUDIO_DESCRIPTOR_ASSETS),
    ("BrickFontDescriptor", BRICK_FONT_DESCRIPTOR_ASSETS),
    ("BrickOneShotAudioDescriptor", BRICK_ONE_SHOT_AUDIO_DESCRIPTOR_ASSETS),
    ("BrickWheelEngineAudioDescriptor", BRICK_WHEEL_ENGINE_AUDIO_DESCRIPTOR_ASSETS),
];
